### ISSUE TITLE
We should rename our tax records DataFrame. 

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/Tax-Calculator#101]
Our core tax data is currently stored in a DataFrame named "puf." This is misleading since the DataFrame will always contain columns that are not on the IRS public use file (intermediate variables, for instance), and often the public use file won't be involved whatsoever. 

I suggest "records" as a better name.

**Comment by feenberg** [comment]
On Tue, 27 Jan 2015, Matt Jensen wrote:

> 
> Our core tax data is currently stored in a DataFrame named "puf." This is
> misleading since the DataFrame will always contain columns that are not on
> the IRS public use file (intermediate variables, for instance), and often
> the public use file won't be involved whatsoever.

I am confused - are the calculations made for each run stored in the same 
dataframe? Is that worthwhile?

dan

**Comment by MattHJensen** [comment]
Sorry for the confusion; I misspoke. 

The puf class, defined in [`puf.py`](https://github.com/OpenSourcePolicyCenter/Tax-Calculator/blob/master/taxcalc/puf.py) represents our tax data. Each instance of the class holds our tax data in memory during calculations. Since our data may or may not actually come from the IRS public use file, I suggest that we rename both the module and the class.

**Comment by talumbau** [comment]
I agree. I will take this one.

**Comment by talumbau** [comment]
closed via https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/121
