### ISSUE TITLE
Changing the tax rate doesn't change the overall tax

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#112]
Setting, for example, `rt7` to 0.75 should produce more tax (larger `c05200`). It does not.

**Comment by MattHJensen** [comment]
Can we close this?

**Comment by talumbau** [comment]
This has been resolved and the example in 10 Minutes to taxcalc shows increased revenue in certain brackets by increasing the rate in Plan Y.
