### ISSUE TITLE
gist: json line for parameters

### ISSUE THREAD

**Issue by Amy-Xu** [OpenSourcePolicyCenter/Tax-Calculator#115]
Here’s a sample of three pararmeters in json line format. Each parameter includes attributes indicating their function, start year, whether it should be inflated over time etc. Can i have some suggestions on 1) whether in general this json format can serve the function of storing and retrieving parameters information  2) if so, is there any other attributes we need to add 3) could the layout be improved in any way?

Here’s the link to the sample json line https://gist.github.com/Amy-Xu/9ab206918e88229012e4

**Comment by MattHJensen** [comment]
This seems to serves our purposes to me, with the two potential downside being that

1. The information is not very dense 
2. We can't place year labels right next to the rows. 

@talumbau, @feenberg, @jlyons871, what do you think? 

As for attributes, I wonder whether:

1.  we need the row labels given that we have the start year. 
2.  a "notes" attribute would be helpful where we could specify things like: "this credit expires in 2018 without action from congress"
3. we should have a "IRS form and line number" attribute.

**Comment by MattHJensen** [comment]
Updated the previous comment with a fourth potential attribute.

**Comment by MattHJensen** [comment]
Updated the first comment with notes 5 & 6. Looping @theofanislekkas in as well given the potential webapp links.

**Comment by talumbau** [comment]
I'm way late on this, but here my thoughts:

1. Overall, very much +1. Upcoming PR based on this

2. I like the idea of a `notes` attribute

3. I like the idea of `IRS form and line number`

4. I am +1 on the idea of integrating the naming scheme with how the webapp reads data.

**Comment by MattHJensen** [comment]
Most of this is in #131. Only todo left is to break out the description attribute into three attributes: 'description', 'notes', and 'IRS_reference'.

**Comment by MattHJensen** [comment]
Done and closing.
