### ISSUE TITLE
How should we build instances of class `Calculator`?

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#117]
We are heading in a direction that will soon lead to code like this:

```
tax_dta = pd.read_csv("puf2.csv")
params1 = Parameters.from_file("params.jsonl")
params2 = Parameters.from_file("params2.jsonl")
records = Records(tax_dta)
calc1 = Calculator(params1, records)
calc2 = Calculator(params2, records)
calc2.e00100 += 1000
```
The problem with this is that the Records class (it's still called "PUF" as of this writing, but will be changed soon) was not created as an immutable type. Also, a Calculator instance just keeps the `records` instance as an attribute, so changing `e00100` in calc2 changes `e00100` for calc1 as well.

One resolution would just be to tell people "don't do that." The "correct" way to build the calculators would then be:

```
tax_dta = pd.read_csv("puf2.csv")
params1 = Parameters.from_file("params.jsonl")
params2 = Parameters.from_file("params2.jsonl")
records1 = Records(tax_dta)
records2 = Records(tax_dta)
calc1 = Calculator(params1, records1)
calc2 = Calculator(params2, records2)
calc2.e00100 += 1000
```

Another option would be to create a Calculator constructor that just takes in filenames. This would be succinct and eliminate ambiguity:

```
calc1 = Calculator(parameters="params.jsonl", records="puf2.csv")
calc2 = Calculator(parameters="params2.jsonl", records="puf2.csv")
```

@MattHJensen seemed to express support for this idea.

**Comment by MattHJensen** [comment]
Am I right to think that the main downside of creating a Calculator constructor that takes in filenames would be a reduction in transparency about how the machine works? Anything that I'm missing? 

The pros in my eyes are 1) it takes many fewer steps to build a calculator 2) it would be harder to screw up.

**Comment by talumbau** [comment]
I think you've hit the salient points. Now that a calculator has the "pass through" capabilities (from https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/108) there really isn't much for a user to "do" with a `Parameters` object or a `Records` object.

**Comment by MattHJensen** [comment]
Sounds good to me, then!

**Comment by talumbau** [comment]
closed by https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/126
