### ISSUE TITLE
How should we implement the extrapolation-stage-1 blowup?

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/Tax-Calculator#118]
I integrated the first stage of the data extrapolation in puf.py. This reads in a csv of "blowup factors" and, when increment_year() is called, it blows up the puf data according to a pre-specified mapping between puf variables and the blowup factors. 

[blowup integration at my fork](https://github.com/MattHJensen/taxcalc/blob/master/taxcalc/puf.py)

Please let me know if this integration looks like a reasonable start for now. If so, I will implement stage 2 of the data extrapolation tomorrow, which simply updates the weight variable `s006` for each year, and then submit a PR that we can hopefully merge before renaming everything "puf" to "records".

**Comment by talumbau** [comment]
Looks pretty neat. A few comments:

https://github.com/MattHJensen/taxcalc/blob/master/taxcalc/puf.py#L228
Not sure what is happening here

If the files are not found, I think we should throw an exception and report a good error message.

https://github.com/MattHJensen/taxcalc/blob/master/taxcalc/puf.py#L184
Mixed upper and lower case?

**Comment by MattHJensen** [comment]
@talumbau, I just pushed some changes. Is this how you recommend reporting an error message? 
https://github.com/MattHJensen/taxcalc/blob/master/taxcalc/puf.py#L238-L243

**Comment by MattHJensen** [comment]
Dealt with in #120
