### ISSUE TITLE
Get rid of repeated code

### ISSUE THREAD

**Issue by Copper-Head** [OpenSourcePolicyCenter/Tax-Calculator#12]
Glancing at the code I see a lot of situations where the same code is being rewritten several times in consecutive lines of code. Code repetition is dangerous for the following reasons:
1. It doesn't capture commonalities between procedures.
2. On a more practical note, imagine a situation where you decide to modify this code? Would you rather modify it once and have your change percolate everywhere appropriate or would you prefer to manually find every instance where that code is used and hope that you neither missed nor made a typo in any of them?

I propose we simply find all instances of repeating code, set it to variables whenever possible. 
P.S.
In the case of some operations (like constructing boolean arrays), this might even give us a tiny bit of a speedup. I'm positively obsessed with speed now :)

**Comment by MattHJensen** [comment]
Closing.
