### ISSUE TITLE
Commenting Convention for functions.py

### ISSUE THREAD

**Issue by Amy-Xu** [OpenSourcePolicyCenter/Tax-Calculator#123]
I’m thinking about the commenting convention for functions.py. Here are some of my thoughts.

- at function level

The documentation can include two sections for each function, a docstring section and pure comments. The docstring section includes the information like methods functionality and key parameter description that needs to be able to easily retrieve to a web documentation page. The pure comments give more detailed explanation for each section of the code, to help people who actually read the code follow the tax logic better.

In the docstring section, there might be three parts in many cases. The first part indicates the name of the tax/credit/adjustment and the reference to IRS form, followed by the second part which is a brief description of the function. Then we have last part for important parameters, input variables, output variables and intermediate variables. Parameters should be the most important piece of information here as most users want to manipulate and should be able find them easily. So they are put in the first place. Input variables are either categorized in general categories, because there are so many of them, or a reference is given to the function where the variable was calculated. Output variables are the tax/credit/adjustment result of this function, which is meant to differentiate from the intermediate variables. The output variables are calculated in the same section but used later on in some other functions. In a word, in this docstring section, I tried not only to give essential information about one particular function, but also to help users understand how the function interact.

- at the package level

There are some global variables like puf and _cmp in functions.py. These we should explain before all of the functions so we don’t need to repeat it at function level.

Here's an example of comments for three functions. 
https://gist.github.com/Amy-Xu/afc44f04263705789d4e

Please let me know if you have any thoughts/suggestions.

**Comment by talumbau** [comment]
I like this style. My only comment is to have just one doc string instead of a series of doc strings. You can just leave a blank line. We might have to parse out the different sections but that should be OK. In general, I am a fan of the "numpy-style" doc strings.

**Comment by MattHJensen** [comment]
@talumbau and @jlyons871 do you think this style will play well with sphynx/readthedocs?

**Comment by talumbau** [comment]
If we have a standard doc string, i.e.:

```
def foo():
    """
    Everything here
    """
    pass
```

We will be good to go with sphynx and readthedocs

**Comment by Amy-Xu** [comment]
@MattHJensen just to confirm we are using just one doc string for each function?

**Comment by MattHJensen** [comment]
Yea, let's follow T.J.'s advice on this. One doc string, a blank line to separate out section, and generally 'numpy-style' doc strings

**Comment by MattHJensen** [comment]
Closing this in favor of #244
