### ISSUE TITLE
the taxcalc package should support a `warm_up` function

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#128]
In a typical use case for using the calculator, the first call to `calc_all` invokes the numba compilation process through `numba.jit`. Subsequent calls to `calc_all` already have the functions compiled, so they go very quickly. 

For the web application, a similar scenario was envisioned. The first call to the calculator would invoke the compiler, but subsequent calls would be fast. However, because of the failsafe nature of the work queue, and the desire to prevent memory leaks, redis queue will fork a new process each time a chunk of work is created. The forked process will not have the compiled assets from the parent process, so each calculation (i.e. production of the table) pays the compilation penalty. This is unfortunate and will effect performance of the webapp.

If we create `taxcalc.warm_up()`, it seems likely that we can invoke this function when the worker spins up, before it is given any work. Then, when the worker is called upon to do work, the compilation will have already occurred, thus providing the desired performance benefits.

This would also allow users to put `taxcalc.warm_up()` at the top of the IPython notebooks, to provide a speedier interactive session.

**Comment by MattHJensen** [comment]
:+1

**Comment by talumbau** [comment]
this is no longer needed due to the use of a gevent thread pool in celery.
