### ISSUE TITLE
10-yr tables should allow behavioral effects

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/Tax-Calculator#137]
For the 10-yr table generators, we should have an option to incorporate behavioral effects. Behavioral effects should be incorporated for each year separately. 

@Amy-Xu is planning to take this one (seeking guidance where needed from @talumbau) after #130 and #135 are merged.

**Comment by talumbau** [comment]
adding `tax` label.

**Comment by MattHJensen** [comment]
This can be done by using a calc_y_behavior and calc_x calculators.
