### ISSUE TITLE
Only parameters that have `cpi_inflated` set to True should be inflated

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#139]
When reading parameters, we use the `expand_array` function to fill out the parameter values for the budget window. Currently, every parameter is inflated by a constant inflation rate. Only parameters that have `cpi_inflated` set to True in their metadata should have this behavior.

**Comment by MattHJensen** [comment]
@talumbau this is the blocking issue for testing right now.

**Comment by talumbau** [comment]
should have this up in < an hour.

**Comment by MattHJensen** [comment]
Dealt with in https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/146. Closing.
