### ISSUE TITLE
Table creation example (with a new plan-y json file) should exist in the notebook.

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#140]
This is a typical user story and so should be in the example notebook.

**Comment by MattHJensen** [comment]
I am dealing with this in #201, but may break the notebook out into a new PR

**Comment by MattHJensen** [comment]
Discussing in #240

**Comment by talumbau** [comment]
10_Minutes_to_taxcalc notebook has tables. Closing.
