### ISSUE TITLE
`groupby_income_bins` should take an optional list of breakpoints

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#151]
Currently, `groupby_income_bins` has a fixed binning for grouping by AGI. The current bins are:

```
bins = [-1e14, 0, 9999, 19999, 29999, 39999, 49999, 74999, 99999, 200000, 1e14]
```
This bin assignment breaks the records into the following groups: income < 0, income >= 0 and < 10k, income >= 10k and < 20k...., income >= 100,000 and <=200,000, above 200k.

It should be possible to pass a list of breakpoints that would make the breakpoints be whatever you want. The passed in breakpoints would "go to the right". In other words, a value X would indicate to split groups at X, where records with value X would go in the group on the right. So, to duplicate the default behavior one would pass:

```
breakpoints  = [0, 10000, 20000, 30000, 40000, 50000, 75000, 100000, 200001]
gp = groupby_income_bins(df, breakpoints)
```

The number of groups would always be: len(breakpoints) + 1

**Comment by talumbau** [comment]
I need this so that the webapp can drive desired behavior and not always require the same binning all the time.

**Comment by talumbau** [comment]
On second thought, let's not try to out-think pandas. The function will take a `bins` argument and the boolean `right` (default to `True`). These will be passed directly to pandas `cut`

**Comment by feenberg** [comment]
On Thu, 26 Feb 2015, T.J. Alumbaugh wrote:

> 
> bins = [-1e14, 0, 9999, 19999, 29999, 39999, 49999, 74999, 99999, 200000, 1e
> 14]
> 
> This bin assignment breaks the records into the following groups: income <
> 0, income >= 0 and < 10k, income >= 10k and < 20k...., income >= 100,000 and
> <=200,000, above 200k.
> 
> It should be possible to pass a list of breakpoints that would make the
> breakpoints be whatever you want. The passed in breakpoints would "go to the
> right". In other words, a value X would indicate to split groups at X, where
> records with value X would go in the group on the right. So, to duplicate
> the default behavior one would pass:
> 
> breakpoints  = [0, 10000, 20000, 30000, 40000, 50000, 75000, 100000, 200001]
> gp = groupby_income_bins(df, breakpoints)


I don't think we can allow the website users to specify the bins without 
causing problems for the disclosure promises we are making to SOI.

dan

**Comment by talumbau** [comment]
that's a good point. This feature would not be accessible to users of the webapp, but rather we would hardcode the bins in the code that deploys the site. That way, we would only have to change code assets that control the webapp if/when we want to change the bins, instead of deploying a new version of the calculator.

**Comment by talumbau** [comment]
closed via https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/153
