### ISSUE TITLE
Net Investment Income Tax

### ISSUE THREAD

**Issue by Amy-Xu** [OpenSourcePolicyCenter/Tax-Calculator#163]
This Net Income Income Tax (NIIT), also referred as Unearned Income Medicare Contribution Tax, was originally added to c05750 (Tentative income tax before credits) in MUI() but not the final result of tax revenue. Right now moved it from c05750 to _othertax to make sure it's included in the final _ospctax.

#162 @MattHJensen Could you review and merge it?

**Comment by MattHJensen** [comment]
Dealt with in #162. Closing.
