### ISSUE TITLE
_numextra if condition

### ISSUE THREAD

**Issue by Amy-Xu** [OpenSourcePolicyCenter/Tax-Calculator#174]
`

    if puf:
        if FDED == 2 and e04470 > STD[MARS - 1]:
            if MARS != 2:
                _numextra = (e04470 - STD[MARS - 1])/float(STD_Aged[0])
            else:
                _numextra = (e04470 - STD[MARS - 1])/float(STD_Aged[1])
        elif e02400 > 0:
            _numextra = float(_txpyers)
        else:
            _numextra = 0.
    else:
        _numextra = float(AGEP + AGES + PBI + SBI)

`

In this snippet, we use the extra standard deduction for aged/blind taxpayers (STD_Aged) according to their filing status (MARS), ultimately to get the number of extra standard deduction for each taxpayer (_numextra). 

From the instruction for form 1040, we can see that one unit of extra deduction is 1550 for single and head of household  (MARS==1 and 4) , and 1200 for married filing jointly and married filing separately (MARS==2 and 3). However, currently we are applying 1550 to all filing status other than married filing jointly, which is slightly different from 1040 instruction.

I think the logic should probably look like this:
`

            if MARS != 2 and MARS !=3:
                _numextra = (e04470 - STD[MARS - 1])/float(STD_Aged[0])
            else:
                _numextra = (e04470 - STD[MARS - 1])/float(STD_Aged[1])

`

@MattHJensen what do you think?

**Comment by MattHJensen** [comment]
@Amy-Xu, that seems right to me. Dealing with it in #170.

**Comment by MattHJensen** [comment]
Dealt with in #170. Closing.
