### ISSUE TITLE
The capital gain subject to 20% rate

### ISSUE THREAD

**Issue by Amy-Xu** [OpenSourcePolicyCenter/Tax-Calculator#175]
`

         if c24540 gt _brk6{FLPDYR,MARS} then 
            _addtax = .05*c24517;
         else if _taxinc gt _brk6{FLPDYR,MARS} then 
            _addtax = .05*min(c04800-_brk6{FLPDYR,MARS},c24517);
         else 
            _addtax = 0;

`

This snippet deals with the extra 5% capital gain tax starting in 2013 for capital gain and dividend above 39.6% regular tax rate threshold. We apply the extra 5% to entire capital gain if ordinary income is above bracket 6, which implies all capital gain should be tax at 20%. If total taxable income is above bracket 6 but ordinary income is not, we just tax the capital gain exceeding bracket 6 at 20%. 

@feenberg Do I understand this snippet right? Please correct me if I misunderstand anything. 

I also have two questions for you @feenberg. 

First, should we use _dwks21 instead of c24517 here? Even though c24517 indeed is the capital gain excluding 25% and 28% gain, in the Schedule D Tax Worksheet (inside Schedule D instruction), it checks this c24517 against taxable income (@line 21 in 2014 form; @line20 in 2008 form; @line21 in 2007 form) and correspondingly we use the variable named _dwks21 as the base in the SAS code for the 15% rate capital gain tax. 

Second, why are we using c04800 (taxable income) instead of _taxinc here in this snippet? 

Thanks!! @feenberg 

@MattHJensen Could you take a look at this snippet when you have a chance? 

I also tried to match the variables in the code to the fields in Schedule D Tax Worksheet (2007). http://www.irs.gov/pub/irs-prior/i1040sd--2007.pdf
Here are my notes (in form of: line number - variable name) if somehow helpful.
1 - _taxinc
2 - c00650
3 - e58980
4 - e58990
5 - _dwks5
6 - c24505
9 - _dwks9
10 - c24516
12 - _dwks12
13 - c24517
14 - c24520
15 - c24530
16 - _dwks16
17 - _dwks17
18 - c24540
19 - c24534
21 - _dwks21
23 - c24597
24 - c24598
25 - _dwks25
26 - _dwks26
28 - _dwks28
29 - c24610
30 - c24615
31 - _dwks31
32 - c24550
33 - c24570
34 - c24560
35 - _taxspecial
36 - _xyztax
37 - c24580

**Comment by feenberg** [comment]
I'll get back to you on Thursday - preoccupied this evening and tomorrow.

dan

**Comment by feenberg** [comment]
On Tue, 10 Mar 2015, Amy Xu wrote:

> 
> `
>
>      if c24540 gt _brk6{FLPDYR,MARS} then
>         _addtax = .05*c24517;
>      else if _taxinc gt _brk6{FLPDYR,MARS} then
>         _addtax = .05*min(c04800-_brk6{FLPDYR,MARS},c24517);
>      else
>         _addtax = 0;
> 
> `
> 
> This snippet deals with the extra 5% capital gain tax starting in 2013 for
> capital gain and dividend above 39.6% regular tax rate threshold. We apply
> the extra 5% to entire capital gain if ordinary income is above bracket 6,
> which implies all capital gain should be tax at 20%. If total taxable income
> is above bracket 6 but ordinary income is not, we just tax the capital gain
> exceeding bracket 6 at 20%.
> 
> @feenberg Do I understand this snippet right? Please correct me if I
> misunderstand anything.

Yes, that is my understanding of what the rules are.

> 
> I also have two questions for you @feenberg.
> 
> First, should we use _dwks21 instead of c24517 here? Even though c24517
> indeed is the capital gain excluding 25% and 28% gain, in the Schedule D Tax
> Worksheet (inside Schedule D instruction), it checks this c24517 against
> taxable income (@line 21 in 2014 form; @line20 in 2008 form; @line21 in 2007
> form) and correspondingly we use the variable named _dwks21 as the base in
> the SAS code for the 15% rate capital gain tax.
>

There are two uses of c24517. Note that if nongain income is greater than 
bracket6, the _dwks21 must equal c24517, so the first use doesn't matter 
which is used. In the second use it does matter, and you are correct to 
notice that _dwks21 would be correct.

> Second, why are we using c04800 (taxable income) instead of _taxinc here in
> this snippet?

Because we were wrong? _taxinc will be better in the rare cases when they 
are different.

dan

**Comment by Amy-Xu** [comment]
Should I make these changes now? @MattHJensen

**Comment by MattHJensen** [comment]
Sounds great. Closing issues :+1:
