### ISSUE TITLE
fix imputation of _compitem

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/Tax-Calculator#178]
_compitem records whether a taxpayer is a compulsory itemizer, i.e., is he an itemizer even though the standard deduction would have been larger than his total itemized deduction. We attempt to determine whether someone is a compulsory itemizer by checking:

    if e04470 > 0 and e04470 < STD[MARS-1]:
        _compitem = 1.
     else: _compitem = 0. 

However, e04470 (p04470) in the puf is the taxpayer's total deduction amount, not necessarily their itemized deduction amount. Therefore, e04470>0 doesn't ensure that the taxpayer was an itemizer. Instead we should use FDED==1. 

Moreover, `FDED == 1 and e04470<STD` does not ensure that the taxpayer was a compulsory itemizer since the standard deduction has increased since 2008 and so the taxpayer could meet this condition without being a compulsory itemizer if his itemized deduction amount is greater than the 2008 standard deduction amount but less than the current_year standard deduction amount. 

We can resolve this issue by comparing `e04470` to the 2008 standard deduction amount rather than the current_year standard deduction amount. 

Dealing with both of these issues in #170.

**Comment by feenberg** [comment]
On Wed, 11 Mar 2015, Matt Jensen wrote:

> 
> _compitem records whether a taxpayer is a compulsory itemizer, i.e., is he
> an itemizer even though the standard deduction would have been larger than
> his total itemized deduction. We attempt to determine whether someone is a
> compulsory itemizer by checking:
> 
> if e04470 > 0 and e04470 < STD[MARS-1]:
>     _compitem = 1.
>  else: _compitem = 0. 
> 
> However, e04470 (p04470) in the puf is the taxpayer's total deduction
> amount, not necessarily their itemized deduction amount. Therefore, e04470>0
> doesn't ensure that the taxpayer was an itemizer. Instead we should use
> FDED==1.

Yes, you are right.

dan

**Comment by MattHJensen** [comment]
Dealt with in #170. Closing.
