### ISSUE TITLE
Add a results row to the distribution and difference tables

### ISSUE THREAD

**Issue by jlyons871** [OpenSourcePolicyCenter/Tax-Calculator#181]
In both DataFrames returned by `utils.create_distribution_table()` and `utils.create_difference_table()`, a "results" row (at the bottom) needs to be added. This will contain a sum of all the corresponding data for that column, from all of the rows.

**Comment by talumbau** [comment]
it's probably more accurate to call it a "sum" or "all" row, rather than "results", but yes it is basically just a sum.

**Comment by MattHJensen** [comment]
Resolved. Closing.
