### ISSUE TITLE
When a user supplies one year of a multi-year parameter, what should we do?

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#187]
There is an ambiguity in what it means for a user to supply values for a parameter when the default value of that parameter has values for multiple years. As an example, consider `_STD_Aged` and its current defaults:

```
      _STD_Aged:      [[1500, 1200],
   	                  [1550, 1200],
	                  [1550, 1250]]
```
There are values for "married" and "unmarried" for three years. To calculate for a full 10 budget years (years 4 through 10), we increment with either a default inflation rate or a user-supplied inflation rate. Now suppose the user supplies (either through the web app or manually through the `mods` keyword argument) one year of values: `_STD_Aged = [[1525, 1225]]`. It seems to me that there are two options:

- fill in years 2 and 3 based on the defaults, then fill in the rest of the values with the proper inflation calculation (years 4 through 10)

- fill in years 2 through 10 with the proper inflation calculation.

@MattHJensen, @Amy-Xu do you have thoughts on this?

**Comment by MattHJensen** [comment]
I believe we should do the second, assuming my understanding is correct: 

Let's say defaults for var X are [[1], [2], [3]] for 2013, 2014, and 2015. Then the user replaces the 2013 value with 4. I advocate that the behavior is:

1. If X is cpi inflated, then X = [[4], [4*(1+CPI)], [4*(1+CPI)**2], [4*(1+CPI)**3],...]
2. If X is not cpi inflated, then X = [[4],[4],[4],...]

Also a side-note; I just want to verify that the webapp is starting at 2015, so the user can enter params for 2015-2024.

**Comment by talumbau** [comment]
OK. That makes sense to me. Can you show me what it would look like to start the calculator at 2015? As in, which file do I use and what arguments do I pass to the Calculator constructor?

**Comment by MattHJensen** [comment]
I think the easiest way right now is to load the calculator using the standard method and then run increment_year() twice.

**Comment by talumbau** [comment]
but use puf.csv, correct?

**Comment by MattHJensen** [comment]
Correct. I just meant that we should to be taking inputs and reporting results for 2015-2024 rather than 2013 - 20xx.

**Comment by feenberg** [comment]
On Thu, 19 Mar 2015, T.J. Alumbaugh wrote:

> 
> There is an ambiguity in what it means for a user to supply values for a
> parameter when the default value of that parameter has values for multiple
> years. As an example, consider _STD_Aged and its current defaults:
>
>       _STD_Aged:      [[1500, 1200],
>                       [1550, 1200],
>                       [1550, 1250]]
> 
> There are values for "married" and "unmarried" for three years. To calculate
> for a full 10 budget years (years 4 through 10), we increment with either a
> default inflation rate or a user-supplied inflation rate. Now suppose the
> user supplies (either through the web app or manually through the mods
> keyword argument) one year of values: _STD_Aged = [[1525, 1225]]. It seems
> to me that there are two options:
>
>  * 
>
>     fill in years 2 and 3 based on the defaults, then fill in the rest of
>     the values with the proper inflation calculation (years 4 through 10)
>
>  * 
>
>     fill in years 2 through 10 with the proper inflation calculation.
> 
> @MattHJensen, @Amy-Xu do you have thoughts on this?

I would think the best approach would be to accept the user supplied 
values where they are given, and inflate those values to any subsequent 
years for which they are not given by the user. Once we get to a year for 
which the user has given a value, accept that value and inflate for 
sugsequent years. The values should be reported in the output whereever 
they differ from the defaults, as inflated.

That allows a minimum of user input for permanent changes, but temporary 
changes require the user to figure out the value at reversion. I would 
leave improving that for Phase II.

dan

**Comment by feenberg** [comment]
On Thu, 19 Mar 2015, Matt Jensen wrote:

> 
> I believe we should do the second, assuming my understanding is correct:
> 
> Let's say defaults for var X are [[1], [2], [3]] for 2013, 2014, and 2015.
> Then the user replaces the 2013 value with 4. I advocate that the behavior
> is:
>
>  1. If X is cpi inflated, then X = [[4], [4(1+CPI)], [4(1+CPI)2],
>     [4*(1+CPI)3],...]
>  2. If X is not cpi inflated, then X = [[4],[4],[4],...]

Possibly we should have a check box for "Inflate the AMT exemption even 
though the law doesn't say so (yet)".

dan

**Comment by MattHJensen** [comment]
On Mar 19, 2015, at 3:27 PM, feenberg <notifications@github.com<mailto:notifications@github.com>> wrote:



On Thu, 19 Mar 2015, Matt Jensen wrote:

>
> I believe we should do the second, assuming my understanding is correct:
>
> Let's say defaults for var X are [[1], [2], [3]] for 2013, 2014, and 2015.
> Then the user replaces the 2013 value with 4. I advocate that the behavior
> is:
>
> 1. If X is cpi inflated, then X = [[4], [4(1+CPI)], [4(1+CPI)2],
> [4*(1+CPI)3],...]
> 2. If X is not cpi inflated, then X = [[4],[4],[4],...]

Possibly we should have a check box for "Inflate the AMT exemption even
though the law doesn't say so (yet)”.

Agreed. The intent is to provide an inflation checkbox for every parameter that is not a rate.

dan

**Comment by talumbau** [comment]
The consensus of this issue (take user param and inflate from there) is handled in https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/204
