### ISSUE TITLE
Records.increment_year is probably not doing the right thing.

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#191]
I was just double checking this code and saw this:

https://github.com/OpenSourcePolicyCenter/Tax-Calculator/blob/master/taxcalc/records.py#L86

It appears that `blowup` is not being called in `increment_year`. 

@MattHJensen, please confirm.

**Comment by MattHJensen** [comment]
Blowup should be called in increment_year. Investigating!

**Comment by MattHJensen** [comment]
@talumbau, this seems to be working fine. Am I missing something? Check e00200 before and after increment_year()

**Comment by talumbau** [comment]
Oh I see what you are doing now. `blowup` is a property, which means you can access it with just `self.blowup`. However, it is a property that doesn't return anything. It is basically a method call without the `()`. This confused me enough that I didn't actually understand until the third time I looked at it. I would recommend making `blowup` just a standard method on `Calculator`, especially since it returns nothing. Is that OK with you?

**Comment by MattHJensen** [comment]
Yes, that sounds like an improvement.

**Comment by talumbau** [comment]
ok. will do.
