### ISSUE TITLE
The education credit calculation is not assigned to the appropriate variable

### ISSUE THREAD

**Issue by xiyuw123** [OpenSourcePolicyCenter/Tax-Calculator#218]
In the current master branch, there is no code to set nonrefundable education credits (c07230) to any value, resulting in a value of 0 in the final calculation. This is corrected in the pull request "Education credit changes" for 2012 and later. For 2011, the tax logic for the nonrefundable education credits is slightly different.

**Comment by MattHJensen** [comment]
Resolved with #217. Closing.
