### ISSUE TITLE
Impute education characteristics for refundable credit

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/Tax-Calculator#225]
We do not have all of needed taxpayer characteristics on the puf to compute the refundable portion of the education credits. We might impute these from the [NPSAS](https://nces.ed.gov/surveys/npsas/)

**Comment by MattHJensen** [comment]
@GoFroggyRun was this resolved with the new variables on the 09 puf?

**Comment by GoFroggyRun** [comment]
@MattHJensen  Yes. Both the American Opportunity Credit and the Lifetime Learning Credit are now available in 09 PUF.

**Comment by MattHJensen** [comment]
Could you look to see what we are calculating the value of those credits as in 2013 and what SOI shows the value of those credits as in 2013?

**Comment by GoFroggyRun** [comment]
OK. Will do.

**Comment by GoFroggyRun** [comment]
So I have a stupid question in mind while dealing with this issue: [the code](https://github.com/OpenSourcePolicyCenter/Tax-Calculator/blob/master/taxcalc/functions.py#L1300-L1303) here seems to use an e-value assigned to the American Opportunity Credit, `c87521`, after a bunch of calculation of it. Is this what we really want? If so, should we include `e87521` (aka `p87521`) in our blowup function? Please advice. @MattHJensen

**Comment by MattHJensen** [comment]
@gofroggyrun, yes, I believe we should be blowing up p87521. Not sure what the best blowup factor to apply would be. cc @Amy-Xu

**Comment by GoFroggyRun** [comment]
@MattHJensen @Amy-Xu 
I noticed that we actually have `e87550`, the Lifetime Learning Credit, blowed-up in records.py [here](https://github.com/OpenSourcePolicyCenter/Tax-Calculator/blob/master/taxcalc/records.py#L620) although it hasn't been used in fucntions.py at all. I think it might be reasonable to blow-up `p87521` the same way as we did for `e87550`.

**Comment by feenberg** [comment]
On Thu, 15 Oct 2015, Sean.Wang wrote:

> 
> So I have a stupid question in mind while dealing with this issue: the code here seems
> to use an e-value assigned to the American Opportunity Credit, c87521, after a bunch
> of calculation of it. Is this what we really want? If so, should we include e87521
> (aka p87521) in our blowup function? Please advice. @MattHJensen

In the PUF that is all you can do. There is a calculation for the complete 
file.

dan

**Comment by GoFroggyRun** [comment]
@MattHJensen 
So the actually data for American Opportunity Credit from CBO is $21 billion and we are having a weighted average of $22.5 billion. The difference is seizable and I think we are happy with what we have.

**Comment by MattHJensen** [comment]
Sounds good. Thanks for looking into this @GoFroggyRun. Closing.
