### ISSUE TITLE
Interest paid deduction extrapolation is way off

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/Tax-Calculator#228]
We are currently blowing up the interest paid deduction, which includes mortgage interest and business interest, with the personal income blowup factor. However, mortgage interest deduction amounts fell much farther than personal income between 2008 and 2012 according to SOI tables. We plan to solve this by using the SOI data on the mortgage interest deduction from SOI to develop the blowup factor between 2008 and 2012, and then reverting to personal income thereafter.

**Comment by Amy-Xu** [comment]
PR #231 deals with this issue

**Comment by MattHJensen** [comment]
Dealt with in #231. Closing.
