### ISSUE TITLE
What is the proper format for "row_label" in params.json?

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#241]
Some values of `row_label` are `[2013, 2014, 2015]`. Some are `["2013", "2014", "2015"]`. We should be consistent. It is OK if the value for `row_label` is empty (i.e. it is `""`), but if a value is present, it should be consistent. I would advocate for a list of strings, so  `["2013", "2014", "2015"]`

**Comment by MattHJensen** [comment]
List of strings seems fine to me, although I'm unsure of the pros/cons of that versus a list of ints.

**Comment by zrisher** [comment]
I could see going either way:

Pro string
* it's more likely a consumer of this datapoint would be presenting it than doing math on it
* most of the data in params.json is strings

Pro int
* All of the data in params.json is currently natively typed - true/false, ints, etc. No other field is a type other than its most basic form.
* Slightly smaller data size

I think the greatest consistency would be achieved by either storing it as an int, or storing it as a string and changing `start_year` to a string. In the former case, you know everything is stored in its most native data type. In the later, you know values/cpi-toggle are stored as their native types and everything else is a string.

**Comment by Amy-Xu** [comment]
Should I go ahead change all row_labels to string? @MattHJensen

**Comment by MattHJensen** [comment]
That sounds good to me.

**Comment by Amy-Xu** [comment]
It seems all the row_labels are already strings on master branch. Do we want to switch start_year to strings as well? If so, I also need to change parameter.py a little bit because currently it's read in as int.

**Comment by MattHJensen** [comment]
@talumbau, what do you think?

**Comment by talumbau** [comment]
I am fine with `start_year` as an integer, but perhaps that is confusing. Mostly just a fan of a uniform choice throughout.

**Comment by talumbau** [comment]
I think the consensus is: `row_label` will be a list of strings. Other naming convention topics can be raised in separate issues. closing.
