### ISSUE TITLE
review the additional child tax credit for accuracy

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/Tax-Calculator#247]
@feenberg mentioned that the additional child tax credit changed between 2012 and 2013. I noticed that it will revert back after 2017. We should review our logic to ensure that it reflects the latest law. 

http://www.hrblock.com/taxes/partner/article.jsp?otpPartnerId=180&articleId=35

**Comment by MattHJensen** [comment]
@GoFroggyRun, could you look into this?

**Comment by GoFroggyRun** [comment]
@MattHJensen Sure. No problem.

**Comment by GoFroggyRun** [comment]
The reversion in the future years has been perfectly taken care of by parameters `_ACTC_Income_thd` and `_CTC_c`, which all have correct values correspondingly. @MattHJensen

**Comment by MattHJensen** [comment]
Thanks @GoFroggyRun
