### ISSUE TITLE
Explore ways to avoid passing params to iterator_jit decorator

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/Tax-Calculator#263]
Currently we must pass parameter names to iterator_jit in order to indicate which variables should not be iterated over (the params are 1 dimensional at this point; records are not).  

This is onerous, and requires quite a bit of explanation to users, many of whom may not need or want to know the architecture of the rest of the calculator. 

Options that we have considered:
1. Determine which variables should not be iterated over by examining params.json or perhaps a dictionary that indicates whether a variiable is a record's attribute or a parameter's attribute at compile time.
2. Expand the parameters to match the length of our taxpayer attributes.

**Comment by talumbau** [comment]
This was resolved (using the first option listed above) in https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/287. Closing.
