### ISSUE TITLE
_AMT_CG_thd* parameters need proper col_label in params.json

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#266]
`_AMT_CG_thd1` and `_AMT_CG_thd2` are multi-valued parameters in `params.json`, but they have an empty string for `col_label`. This causes a problem for the webapp because it parses the JSON and uses  `col_label` to figure out if it should make the field a multi-column field on the website, like this:

![oscp_multi_col](https://cloud.githubusercontent.com/assets/1891418/7643815/83193e82-fa62-11e4-8f68-35e6de7e1b27.png)

The empty string for `col_label` confuses the logic of the form renderer. This was the ultimate cause of the bug I was seeing earlier today in trying to implement https://github.com/OpenSourcePolicyCenter/webapp/issues/170. 

So, appropriate column labels for these parameters should be added. I believe it is appropriate to break in this case (in other words, I don't think we should change the logic of the webapp), because a consistent multi-value parameter should have column labels to describe what the different values mean. I would welcome dissenting thoughts on this, but it seems like a good way for the webapp to work.

**Comment by MattHJensen** [comment]
This should be "MARS" for both. I'm agreed that it is fine for it to break here.
