### ISSUE TITLE
is the Taxer function doing what is desired?

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#29]
It seems like the Taxer function is doing quite a bit of logical work to set variable `_a5`. Then, it sets the value of `_a6` based on some logical conditions and the values `_a3` and `_a5`. Immediately after this though, there is the line:

```
_a6 = inc_in
```

The computed results (`inc_out`) only involve `_a6` and other values from outside the function, so none of the work for variables `_a1` - `_a5` is used. I commented out that code and got the same answer. Am I missing something?

https://github.com/OpenSourcePolicyCenter/Tax-Calculator/blob/master/translation.py#L1738-L1740

**Comment by MattHJensen** [comment]
Closing.
