### ISSUE TITLE
Which users will install taxcalc via conda and which will use source? 

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/Tax-Calculator#290]
From Martin:

> While I am waiting for reactions to my pull request, I decided to
look over the Installation section of the README.md file, which
is the first thing somebody who is interested in getting started
with the Tax Calculator will read.

> My overall reaction is that the README.md Installation
instructions are not well designed to get people started and, in
fact, are likely to discourage people from getting started
with the Tax Calculator.  My experience is based on creating
a new Mac user and trying to follow the Installation instructions.
My experience was a bit like opening *War and Peace* in the
middle of the book and starting to read: pretty confusing.

> I would have tried to prepare a pull request for modifications
of README.md, but have no idea about how to approach
revisions.  Here are some notes I made while trying to follow
the instructions:

> (a) In the first section beginning with "The taxcalc package is
installable via" the "python setup.py install" command does nothing
even if python is installed (as, say, on a Mac).  Where is the setup.py
file supposed to be located on the local computer?  Or, if it to be
downloaded, how does an interested party do that?

> (b) Even if the Anaconda distribution of Python is installed
(which the Installation section says nothing about), the command
"conda install -c ospc taxcalc" does work, but there are two major
problems:

> First, this command's output says NOTHING about where taxcalc
is installed.  After much looking, I found it here:
~/anaconda/lib/python3.4/site-packages/taxcalc-0.4.9-py3.4.egg/taxcalc
It is bad form to install an application (the Tax Calculator) in the
same directory tree as the Anaconda tools; certainly the instructions
in the contributor_guide.rst do not call for such an approach.

> And the second problem, is that when the user changes to that directory,
and executes "py.test" (which is something that the documentation,
rightly so, urges people to do) nothing happens except the message
"collected 0 items".  This is probably because there is no tests
subdirectory in the taxcalc directory (as there is when following the
installation instructions in the Contributor Guide).

> (c) The final section begins with "For contributors, the conda recipe
is located in the conda.recipe directory."  But the installation in
step (b) above does not include a conda.recipe file or directory.
So, again, there is nothing but confusion for somebody trying to
get started with the OSPC Tax Calculator.

**Comment by MattHJensen** [comment]
I wholeheartedly agree that the installation section of README.md is
confusing.

What would you think of something along the lines of the snippet below
(perhaps written or laid out differently, but expressing this content?)

"The taxcalc package is currently available to contributors. To get
started, please read our contributor guide <
http://taxcalc.readthedocs.org/en/latest/contributor_guide.html>.

If you would like to access the package through our web application, please
email matt.jensen@aei.org about becoming a beta tester for our TaxBrain web
application at ospc.org."

This kicks the can down the road a bit, but I’m not sure we are ready to
interact with the type of user who only wants to use the taxcalc package
api without digging into the source; and if someone does want to dig into
the source, I’d like to encourage them to be set up with git and
contribute.

**Comment by MattHJensen** [comment]
Implementation in #289. @talumbau, thoughts?

**Comment by talumbau** [comment]
From the email I can see that there is a context I have in mind that is apparently quite different from the context assumed above. It seems valuable to me to give people the knowledge that, for example, if they run something via the TaxBrain webapp, they can have the exact same code on their machine (either Windows, Mac, or Linux) that ran on the webapp with one command. Perhaps the proper information to include is something like this (towards the bottom of the README): "Conda packages are created for every release of `taxcalc`. You can get the latest package for your platform via the command `conda install -c ospc taxcalc`. That way, if this statement makes no sense to people, they can simply ignore it. For others who actually just want to use the package, they will have the information that they can get the latest release via the `ospc` channel on binstar.

**Comment by MattHJensen** [comment]
@talumbau, yes, I can see how that information would be relevant to someone, especially if he is hearing about TaxBrain. 

@martinholmer, do you think if this were broken into a separate section it would dissuade newcomers from thinking that this is a good way to "get started"?

    Conda Package
    ============

    Conda packages are created for every release of taxcalc. 
    We use them to install taxcalc on AWS worker nodes for the TaxBrain web application. 
    You can get the latest release for your platform via the command `conda install -c ospc taxcalc`.

**Comment by MattHJensen** [comment]
This has been resolved, at least for now with #289 and #297. Closing.
