### ISSUE TITLE
Restructuring __init__ for Record object

### ISSUE THREAD

**Issue by mmessick** [OpenSourcePolicyCenter/Tax-Calculator#294]
While working to incorporate the JSON readability provided by Luca, I was noticing that it might just be better to allow __init__ to take in pre-processed data, rather than reading in the data upon initialization. Or, even better, have a default data set for a Record object and then just a method to override the data we want to add to that object.

**Comment by mmessick** [comment]
@talumbau, Matt said you might be interested in the restructuring of the code architecture, so I would love to know your thoughts. Thanks, Maria

**Comment by talumbau** [comment]
Yes, please do submit a PR with ideas! The interaction with `luca` will probably happen here. Note that we do have a "default" or sorts already: if no argument for `data` is passed, the default is the string "puf.csv", meaning it will attempt to read in a PUF file in the current working directory. I see two potential options here:

- pass in whatever we want to allow as the `data` argument (string, DataFrame, something else), then we do a bit of work to figure out which "thing" we were passed

- create a mutually exclusive set of arguments to `__init__` for the different kinds of arguments (file names, DataFrames, a JSON blob, etc.). Then we just check that the caller didn't specify more than one of them

I think there are multiple "right" answers here.

**Comment by MattHJensen** [comment]
Resolved.
