### ISSUE TITLE
Incorrect calculation of c62100 (Alternative Minimum Taxable Income)

### ISSUE THREAD

**Issue by mmessick** [OpenSourcePolicyCenter/Tax-Calculator#303]
original:

    c62100 = (c00100 - c04470 + min(c17000, 0.025 * max(0., c00100)) + 
            (1-ID_StateLocalTax_HC)*_sit + e18500 - c60260 + c20800 - c21040 )

proposed change:

    c62100 = (c00100 - c04470 + max(0., min(c17000, 0.025 * c00100)) +
                 (1-ID_StateLocalTax_HC)*_sit + c18300 - c60260 + c20800
                  - c21040 + c60130)

these are calculations for when 

    (puf == True and ((_standard == 0 or (_exact == 1 and e04470 > 0))))

**Comment by feenberg** [comment]
On Fri, 10 Jul 2015, mmessick wrote:

> 
> original:
> 
> c62100 = (c00100 - c04470 + min(c17000, 0.025 * max(0., c00100)) +
>         (1-ID_StateLocalTax_HC)*_sit + e18500 - c60260 + c20800 - c21040 )
> 
> proposed change:
> 
> c62100 = (c00100 - c04470 + max(0., min(c17000, 0.025 * c00100)) +
>              (1-ID_StateLocalTax_HC)*_sit + c18300 - c60260 + c20800
>               - c21040 + c60130)
> 
> these are calculations for when (puf == True and ((_standard == 0 or (_exact == 1 and e04470 >
> 0))))
>

It looks to me like this can only make a difference if c17000 is negative. 
I don't think that should happen - c17000 is total medical and dental 
expense.

dan

**Comment by mmessick** [comment]
@feenberg, you're right. That part doesn't make a huge difference, just semantically it matches form 6251 better.

Besides that change, I also got rid of the addition of e18500, because I can't find anywhere in the form where we need to add that in (but please correct me if I'm wrong!). I included the addition of c18300 (the value on line 9 of Schedule A) because it says to add that in on line 3 of Form 6251. I also added in c60130 which is line 6 of Form 6251. I also changed the calculation of c60130, which is discussed in issue #300

**Comment by mmessick** [comment]
@feenberg, I'm actually in the process of changing a few things now so I will update what them for you here when I am done

**Comment by mmessick** [comment]
new proposed change:

    c62100 = (c00100 - c04470 + max(0., min(c17000, 0.025 * c00100)) +
             (1-ID_StateLocalTax_HC)*_sit + c60240 - c60260 + c20800
              - c21040 + c60130)

**Comment by Amy-Xu** [comment]
The proposed change makes sense to me, by comparing the code with schedule A and 6251.

**Comment by mmessick** [comment]
@Amy-Xu and I are discussing ways to make this calculation better.

We think this might be more appropriate:

    c62100 = (c00100 - c04470 + max(0., min(c17000, 0.025 * c00100)) +
             (1-ID_StateLocalTax_HC)*c60240 - c60260 + c20800 - c21040 + c60130)

**Comment by mmessick** [comment]
with reference to issue #173

**Comment by MattHJensen** [comment]
@GoFroggyRun, can we close this one?

**Comment by GoFroggyRun** [comment]
@MattHJensen Yes. The issue has been taken care of.

**Comment by MattHJensen** [comment]
Thanks @mmessick and @GoFroggyRun. closing.
