### ISSUE TITLE
BUG: expand_1D behaves differently from expand_2D when providing inflation rates

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#325]
PR #321  demonstrates a difference in behavior between the two version of `expand_array`. In `expand_1D`, one provides a list of interest rates equal to the desired number of resulting values. Thus, the current behavior is master is as follows:

```
    x = np.array([1, 2], dtype='f4')
    irates = [0.0, 0.1, 0.25]
    exp = np.array([1, 2, 2.5])
    res = expand_1D(x, inflate=True, inflation_rates=irates, num_years=3)
    # res == exp is True
```

The idea is that we desire three scalar values but we only have two. `expand_1D` is implemented such that to get the nth value in the new array, we apply the inflation rate at `irates[n]` to the `n-1` value. This is odd because we never make use of the inflation rate at index 0 (i.e. `irates[0]`).

`expand_2D` takes a different approach: the nth value in the expanded array is based on applying the inflation rate at n-1 to the value at n-1. Thus, to produce an output with k values, we only need k-1 interest rates. 

I think this is more sensical, so I propose that we fix this difference in behavior by modifying expand_1D to work as follows:

```
   x = np.array([1, 2], dtype='f4')
    irates = [0.1, 0.25]
    exp = np.array([1, 2, 2.5])
    res = expand_1D(x, inflate=True, inflation_rates=irates, num_years=3)
    # res == exp is True
```
cc @martinholmer @Amy-Xu

**Comment by martinholmer** [comment]
Pull request #321 resolves the difference in how inflation rates are applied between the
expand_1D() and expand_2D() utility functions in favor of how the expand_1D() function
works.  That decision was based on the acceptance by @MattHJensen after review by
@talumbau of pull request #312, which included the following text in test_parameters.py:
```
# Note: above assert shows that inflation indexing of policy parameters
# works like this:  param(t) = param(t-1) * ( 1 + inflation_rate(t) ).
```
That is, it works like in the expand_1D() function.  However, the current version of the 
expand_2D() function works this way:
```
param(t) = param(t-1) * ( 1 + inflation_rate(t-1) ).
```
So, why does it now seem "more sensical" to apply the indexing in a different way than
was accepted in pull request #312?

Surely the choice should be determined by how CBO applies inflation rates because
the default inflation rates are taken from CBO.  @MattHJensen, what did you find out
about CBO's method after we discussed this issue last month?

**Comment by talumbau** [comment]
It was an oversight on my part to not catch this issue in the previous pull request. The goal for `expand_array` is to take a sequence of values, say,  `[x0, x1, x2]` and create something like `[x0, x1, x2, x3, x4]`, where `x0` is a parameter value for a given year, and `x1` through `x4` are values for the subsequent years (here I mean that `x0` could be scalar or some array). When I was dealing with some of the nuances of `expand_2D` I remember asking @Amy-Xu the question, "If I have a value for a year X and I want to produce the inflated value for year X+1, do I use the inflation rate estimate I am given for year X or year X+1?" At that time, I understood the answer is that I would apply the inflation rate given for year X to my value for year X and get the new value for year X+1. So, I think the first thing is to figure out if I have understood that part correctly.

The underlying idea of `expand_array` is that your values start for some given year and the inflation rates are a list that also starts in the same given year. If my assumption above is correct, it follows that for a `num_years` argument of K, you would only need K-1 inflation rates. Even if my assumption is correct, this is not explicit in the function, and has clearly led to two different implementations, so that could indicate that the safest thing to do is just change the interface entirely.

A more explicit interface might be something like:

```
def expand_array(x, inflate, inflation_rates, start_year, num_years):
```

where `x` is the existing sequence, `inflate` is the bool, `inflation_rates` is now a dictionary of year->rate, start_year is the year associated with `x[0]` and `num_years` is the desired final size. So, we might then have something like:

```
irates = {2000: 0.02, 2001:0.025, 2002:0.027, 2003:0.024, 2004:0.03}
expand_array([4, 5], inflate=True, inflation_rates=irates, start_year=2001, num_years=4)
```
where the answer would be:

```
[4, 5, 5*1.027, 5*1.027*1.024]
```

So, my apologies for muddying the waters here with the two different ways of doing things. Let's first get a definitive answer on the issue of which inflation estimate year (X or X+1) we use to produce the value for year X+1 and then see what makes the most sense from there.

**Comment by martinholmer** [comment]
I concur with your statement:
```
Let's first get a definitive answer on the issue of which inflation estimate year (X or X+1) we 
use to produce the value for year X+1 and then see what makes the most sense from there.
```
Given this approach, I do not understand why you have submitted pull request #326.
Pull request #326 seems premature (and breaks pull request #321, which fixes another
bug in the code).  Why not commit pull request #321 (which makes many improvements
including making inflation indexing **consistent** across 1D and 2D parameters) and then
figure out how CBO applies inflation rates?  Is there anything wrong with this strategy?
If not, why don't you close your pull request #326?

**Comment by MattHJensen** [comment]
>I remember asking @Amy-Xu the question, "If I have a value for a year X and I want to produce the inflated value for year X+1, do I use the inflation rate estimate I am given for year X or year X+1?" At that time, I understood the answer is that I would apply the inflation rate given for year X to my value for year X and get the new value for year X+1. So, I think the first thing is to figure out if I have understood that part correctly.

I may have led everyone astray on this:

Based on [this excel file from CBO](https://www.cbo.gov/sites/default/files/cbofiles/attachments/45066-2015-07-EconomicDataProjections.xlsx) It is my understanding that CBO's inflation rate for year X indicates the amount of inflation that will occur during year X. For example, to find the 2015 price level,  I would multiply the 2014 price level * the 2015 inflation rate.

**Comment by MattHJensen** [comment]
Actually, let me think about this for a few more minutes.... another followup coming soon.

**Comment by martinholmer** [comment]
The **annual** tab of the CBO spreadsheet contains these lines:
```
             2013   2014   2105   2016   2017 ...
PCE Index:  107.3  108.8  110.1  112.1  114.3 ...
% change:     1.2    1.4    1.2    1.9    1.9 ...
```
So, as @MattHJensen said, this shows that the inflation rate in year t is defined
by CBO as the level in year t divided by the level in year t-1.  In other words,
```
X(t) = X(t-1) * ( 1 + inflation_rate(t) )
```
which is exactly what is being **consistently** assumed in pull request #321 and
has been documented in https://github.com/OpenSourcePolicyCenter/Tax-Calculator/blob/master/taxcalc/tests/test_parameters.py#L86-L87
Do you see this issue in the same way, or am I confused?

**Comment by MattHJensen** [comment]
I just want to check to make sure this lines up with how IRS actually applies inflation rates to generate the next year's param value. Will do so as soon as I get back from lunch!

**Comment by feenberg** [comment]
On Tue, 28 Jul 2015, Martin Holmer wrote:

> 
> The annual tab of the CBO spreadsheet contains these lines:
>
>              2013   2014   2105   2016   2017 ...
> PCE Index:  107.3  108.8  110.1  112.1  114.3 ...
> % change:     1.2    1.4    1.2    1.9    1.9 ...
> 
> So, as @MattHJensen said, this shows that the inflation rate in year t is
> defined
> by CBO as the level in year t divided by the level in year t-1. In other
> words,
> 
> X(t) = X(t-1) * ( 1 + inflation_rate(t) )

Is that the average level in x(t) divided by the average in x(t-1) or 
december over december? I am guessing the former.

According to James Young in Taxnotes  Oct 28,2013 the indexed tax law 
parameters are based in the 12 month inflation through Aug of the taxable 
year. That is, inflation from Sep 2012 through Aug 2013 is applied to the 
(unrounded) 2013 parameters to get parameters for the 2014 tax year. I am 
not sure any of this matters to us, but I think that user confusion will 
be minimized if users are asked to supply the t-1 inflation rate to 
determine year t parameter values.

dan

**Comment by martinholmer** [comment]
Thanks @feenberg for clarifying how the actual inflation indexing works given the
time lag in inflation rate statistics.  So, do I understand correctly that we have IRS
doing this (ignoring the partially-offset-year issue) to administer the tax law:
```
X(t) = X(t-1) * ( 1 + inflation_rate(t-1) )
```
while CBO is doing things differently?  That is, doing this:
```
X(t) = X(t-1) * ( 1 + inflation_rate(t) )
```
Or are we making an unwarrented assumption from what is in the CBO spreadsheet?
Maybe when they do tax-law indexing they lag they inflation rate just as the IRS is
forced to do in real time.

I am OK on adopting the IRS administrative approach if all the project team is
in agreement.

**Comment by MattHJensen** [comment]
Yes, @feenberg, thank you! That's exactly the information I wanted to find. In light of this, I'd advocate for moving forward with `X(t) = X(t-1) * ( 1 + inflation_rate(t-1) )` and adding a note to the doc string. I will also double check with John O'Hare when I see him next.

**Comment by talumbau** [comment]
fixed via https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/326

**Comment by talumbau** [comment]
Closing soon if no additional comments. Seems resolved.
