### ISSUE TITLE
Enforce PEP8 Compliance 

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/Tax-Calculator#328]
- [x] Open and then merge a PR that brings current code base to PEP8 compliance. This is forthcoming from me.
- [x] Enforce PEP8 compliance in the test suite. 

This is a followup from the discussion in #30.

**Comment by martinholmer** [comment]
@MattHJensen said on 30-Jul-2015:
> Open and then merge a PR that brings current code base to PEP8 compliance. 
> This is forthcoming from me.
>
>  Enforce PEP8 compliance in the test suite.

Where do things stand on this effort?

**Comment by MattHJensen** [comment]
Latest discussion is in #329. In particular, see the second to last comment.

**Comment by martinholmer** [comment]
So, @MattHJensen, the discussion at the end of pull request #329 is pretty
complicated.  What is the situation?  Are TJ and Jake saying the Travis CI
tool cannot accurately check PEP8-compliant code (and thus, Travis CI is
returning a false negative)?  Or, are they saying they don't know how to 
make the Tax-Calculator code fully PEP8 compliant?

**Comment by MattHJensen** [comment]
The only method that I have discovered to resolve the last PEP8 error (E402) and thereby make the code fully PEP8 compliant is incompatible with our current method of testing with Travis CI. @talumbau has asked @jlyons871 to look into whether we can modify our current method of testing with Travis CI to make it compatible with my E402 fix or whether some other solution to E402 is available. 

Alternatively, I could roll back my fix for E402, we could merge every other PEP8 fix, and then we could start enforcing PEP8 excluding E402 in the test suite. This would buy us time to look for an E402 fix on a more leisurely basis.

**Comment by martinholmer** [comment]
@MattHJensen said:
> Alternatively, I could roll back my fix for E402, we could merge every other PEP8 fix,
> and then we could start enforcing PEP8 excluding E402 in the test suite.
> This would buy us time to look for an E402 fix on a more leisurely basis.

This sounds like an excellent plan to me.

**Comment by MattHJensen** [comment]
Agreed. I will do this tomorrow.

**Comment by MattHJensen** [comment]
Ok, opened #338 in accordance with this plan: 

> Alternatively, I could roll back my fix for E402, we could merge every other PEP8 fix,
> and then we could start enforcing PEP8 excluding E402 in the test suite.
> This would buy us time to look for an E402 fix on a more leisurely basis.

**Comment by MattHJensen** [comment]
Resolved with #338. Closing.
