### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by feenberg** [OpenSourcePolicyCenter/Tax-Calculator#344]
I would like to discuss the output format. There is a surplus of
white space, resulting a need for much additional scrolling viewing online
and much difficulty getting a usable printout. In Chrome I only get to
"Personal Exemptions" in the printout, even in landscape mode with "Print
to fit" selected. Is there some way to get more that I should be aware of? 
Would other browsers work better?

Similar concerns are evident if I copy and paste into a word document.
(Actually, it nearly works in landscape if one chooses the right paste
mode). Is this the browsers fault or can we do something about it? I
easily get 15 columns in portrait mode in my work for Marty, by simply
specifying <xmp> for the tables and printing cells in 8 character widths.

Perhaps we will use PDF for printable output? We still need to get the
output on a landscape 8.5x11 page, which will mean drastically reducing
the whitespace.

The vertical whitespace is also excessive - only a third of the vertical
space is allowed for text, but a half is more than enough. Presently 
even a single table takes more than a page.

The closest I could get to a printable table was to copy to Excel and then
print to fit. That looked pretty good (vertical and horizontal whitespace
are both correct and the font is small but readable. Column headings were
truncated. but we could fix that if headings like "Taxable Income" were
given 2 lines and "Billions of Dollars" shortened to "Billions".

At some point each table we produce will have URL at the bottom that leads
the interested user to exactly that simulation. By making the tables easily
reusable without extensive editing we increase the probability that the URL
is retained, and that is a kind of advertisement for the site.

Lastly, it may be that the revenue table is the only one most users will want
in most runs, and perhaps the others should be optional.

dan
617-863-0343

**Comment by MattHJensen** [comment]
@feenberg,  Would you mind reopening this over at the webapp repo?  (I'm happy to do so as well). https://github.com/OpenSourcePolicyCenter/webapp-public.

**Comment by talumbau** [comment]
will comment on issue when it gets moved to webapp-public

**Comment by feenberg** [comment]
I did enter it on webapp-public, but I am not sure I did it right. Github 
removed most of my newlines and added html markup, so the result is a 
mess. I swear I didn't type any <p>s or </p>s - Github added those.

dan

**Comment by MattHJensen** [comment]
Thanks @feenberg. Closing this issue in favor of https://github.com/OpenSourcePolicyCenter/webapp-public/issues/35. 

I'm not sure where the html markup is coming from, but I'll go ahead and use my admin powers to clean it up a bit.

**Comment by MattHJensen** [comment]
Hmm, I also can not edit out the odd html markup. Perhaps we can keep discussion of that github quirk over here so that OpenSourcePolicyCenter/webapp-public#35 is clean for discussion of the real matter at hand, TaxBrain output formatting.
