### ISSUE TITLE
`p87482` and `p87521` have bad values in the current (2009) PUF

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#358]
They don't appear to be used anywhere in our calculations, but some of the entries in the file are `         .` (a bunch of spaces with a decimal point). This causes the column to be read in to pandas as a string, so the `dtype` of the column is `object`. If we attempted to do math on these columns, we would get an error.

**Comment by Amy-Xu** [comment]
Yes, we have a lot of missing values for those two variables. As we're not using them right now, I didn't deal with those missing values immediately. But @MattHJensen is aware of this issue in 09 PUF and we are going to talk about it with Dan soon.

**Comment by talumbau** [comment]
OK, sounds good. I'll close this and we can re-open or create a new issue if there are action items after the meeting with Dan.

**Comment by feenberg** [comment]
Rather than change the calculator, they should probably be converted to 
zeroes in the SAS step that copies the SOI version of the PUF to our 
version.

dan
