### ISSUE TITLE
Queston: Why are qualified dividends (e00650) not in AGI?

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/Tax-Calculator#366]
On the master branch, it seems as if ordinary dividends (e00600) are being included in _ymod1, and therefore, are being included in AGI (c00100), but qualified dividends (e00650) are not being included in _ymod1, and therefore, are not being included in AGI (c00100).  Is that an accurate description of how the federal income tax law works?  Or is the exclusion of qualified dividends from AGI an oversight?  Or is something else going on here that has completely escaped my attention?

**Comment by martinholmer** [comment]
@MattHJensen, @feenberg, @Amy-Xu , @GoFroggyRun,
Can anyone shed some light on my question in issue #366?

**Comment by feenberg** [comment]
I think e00650 is included in e00600. If you look at the general 
description booklet what does it show on the 1040 first page?

dan

**Comment by martinholmer** [comment]
@feenberg, Thanks for the helpful answer.
