### ISSUE TITLE
Bug in Travis-CI or in SimpleTaxIO calculate method

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/Tax-Calculator#405]
Pull request #404 uncomments a single line of code in test_simpletaxio.py test_3.  The activated test_3 passes just fine on my Mac computer running Python 2.7 (as documented in the pull request #404 comment).

Why is the Travis-CI test failing?  Is it a bug in Travis-CI or a bug in the SimpleTaxIO calculate method?

The SimpleTaxIO calculate method is working fine when called from the validation/tests script on the computers of @MattHJensen and Martin Holmer, and perhaps others.

This is a critical test because its omission has already caused other check-ins to break the SimpleTaxIO class (for example, pull request #379 broke the SimpleTaxIO class and pull request #379 had to be repaired by pull request #389).  The whole point of the Travis-CI system is to prevent this sort of thing from happening.

Note: this problem was pointed out to @talumbau last week, but he got involved in the rush to release the TaxBrain webapp.

**Comment by talumbau** [comment]
I was able to reproduce the failure on Mac and on Linux. It was surprising that I was able to reproduce on Mac. I'm running Mac OS 10.10.5. Here is a screen cap of my About This Mac window:

<img width="305" alt="screen shot 2015-10-19 at 12 30 25 pm" src="https://cloud.githubusercontent.com/assets/1891418/10585528/4729f520-765d-11e5-97f7-70175f4d1f15.png">

@martinholmer what version of Mac OS X are you running? Can you put in the screen cap for your machine?

**Comment by talumbau** [comment]
Although I can't quantify exactly why, this fix:

https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/406

resolves the issue. For some reason, the compiler does not it when certain record columns are int32 instead of int64. This occurs on a Linux 64 machine and a OS X 64 machine. I wondered if the tests were passing on a 32 bit machine, which is why I was asking about Marin's platform when running the tests locally.

**Comment by talumbau** [comment]
One possibility that occurs to me is that the compiler might not like operations like this:

```
int32 OP float64 -> int32
```

in other words, arithmetic with a 32bit integer and a 64 bit floating point, which then gets stored to a truncated 32bit integer. The preferred size for the truncated integer would be 64 bits. I don't know for sure if that applies because I haven't looked closely at the operations for the code that triggers the error, but it seems reasonable to be concerned about mixed float/int operations where the size is different.

**Comment by talumbau** [comment]
@martinholmer yes as you mentioned I suggested the syntax `dtype='int32'` as a replacement for what was in your original code: importing the int32 dtype object itself from the numpy namespace and specifying it directly. Using the string syntax for specifying dtype is idiomatic and was the least modifying change of your original code. In general, I think it is best to have all arithmetic operations on types of the same size unless there is a need not too. So, I would recommend `int64` and `float64` dtypes throughout the code base.

**Comment by martinholmer** [comment]
@talumbau ,
Here is my info on my iMac:
![image](https://cloud.githubusercontent.com/assets/12170745/10586836/57146d26-766c-11e5-8f25-c6eb774866c0.png)

**Comment by talumbau** [comment]
oh also @martinholmer , can you do a `conda list` and paste the output to this issue?

**Comment by martinholmer** [comment]
@talumbau ,  Here is the output on my computer of the ```conda list``` command:
```
iMac2:tax-calculator mrh$ conda list
# packages in environment at /Users/mrh/anaconda:
#
_license                  1.1                      py27_0  
abstract-rendering        0.5.1                np19py27_0  
alabaster                 0.7.3                    py27_0  
anaconda                  2.3.0                np19py27_0  
appscript                 1.0.1                    py27_0  
argcomplete               0.8.9                    py27_0  
astroid                   1.3.6                     <pip>
astropy                   1.0.3                np19py27_0  
atom                      0.3.9                    py27_0  
babel                     1.3                      py27_0  
backports.ssl-match-hostname 3.4.0.2                   <pip>
bcolz                     0.9.0                np19py27_0  
beautiful-soup            4.3.2                    py27_0  
beautifulsoup4            4.3.2                     <pip>
binstar                   0.11.0                   py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.6.3                np19py27_0  
blaze-core                0.8.0                np19py27_0  
blz                       0.6.2                np19py27_1  
bokeh                     0.9.0                np19py27_0  
boto                      2.38.0                   py27_0  
bottleneck                1.0.0                np19py27_0  
casuarius                 1.1                      py27_0  
cdecimal                  2.3                      py27_0  
certifi                   14.05.14                 py27_0  
cffi                      1.1.0                    py27_0  
chaco                     4.4.1                np19py27_0  
clyent                    0.3.4                    py27_0  
colorama                  0.3.3                    py27_0  
conda                     3.18.2                   py27_0  
conda-build               1.8.2                    py27_0  
conda-env                 2.4.2                    py27_0  
configobj                 5.0.6                    py27_0  
cryptography              0.9.1                    py27_0  
curl                      7.43.0                        0  
cython                    0.22.1                   py27_0  
cytoolz                   0.7.3                    py27_0  
datashape                 0.4.5                np19py27_0  
dateutil                  2.1                      py27_2  
decorator                 3.4.2                    py27_0  
docutils                  0.12                     py27_0  
dynd-python               0.6.5                np19py27_0  
enable                    4.3.0                np19py27_2  
enaml                     0.9.8                    py27_0  
enum34                    1.0.4                    py27_0  
fastcache                 1.0.2                    py27_0  
flask                     0.10.1                   py27_1  
freetype                  2.5.2                         2  
funcsigs                  0.4                      py27_0  
future                    0.13.1                   py27_0  
futures                   2.2.0                    py27_0  
gevent                    1.0.1                    py27_0  
gevent-websocket          0.9.3                    py27_0  
greenlet                  0.4.7                    py27_0  
grin                      1.2.1                    py27_1  
h5py                      2.5.0                np19py27_3  
hdf5                      1.8.15.1                      1  
idna                      2.0                      py27_0  
ipaddress                 1.0.7                    py27_0  
ipython                   3.2.0                    py27_0  
ipython-notebook          3.2.0                    py27_0  
ipython-qtconsole         3.2.0                    py27_0  
itsdangerous              0.24                     py27_0  
jdcal                     1.0                      py27_0  
jedi                      0.8.1                    py27_0  
jinja2                    2.7.3                    py27_1  
jpeg                      8d                            1  
jsonschema                2.4.0                    py27_0  
kiwisolver                0.1.3                    py27_0  
launcher                  1.0.0                         3  
lcms                      1.19                          0  
libdynd                   0.6.5                         0  
libpng                    1.6.17                        0  
libsodium                 0.4.5                         0  
libtiff                   4.0.2                         1  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        2  
llvm                      3.3                           0  
llvmlite                  0.5.0                    py27_0  
llvmpy                    0.12.7                   py27_0  
logilab-common            0.63.2                    <pip>
lxml                      3.4.4                    py27_0  
markupsafe                0.23                     py27_0  
matplotlib                1.4.3                np19py27_2  
mistune                   0.5.1                    py27_1  
mock                      1.0.1                    py27_0  
multipledispatch          0.4.7                    py27_0  
networkx                  1.9.1                    py27_0  
nltk                      3.0.3                np19py27_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py27_0  
numba                     0.19.1               np19py27_0  
numexpr                   2.4.3                np19py27_0  
numpy                     1.9.2                    py27_0  
odo                       0.3.2                np19py27_0  
openpyxl                  1.8.5                    py27_0  
openssl                   1.0.1k                        1  
pandas                    0.16.2               np19py27_0  
patsy                     0.3.0                np19py27_0  
pep8                      1.6.2                    py27_0  
pil                       1.1.7                    py27_1  
pillow                    2.8.2                    py27_0  
pip                       7.1.2                    py27_0  
ply                       3.6                      py27_0  
pockets                   0.2.4                     <pip>
psutil                    2.2.1                    py27_0  
ptyprocess                0.4                      py27_0  
py                        1.4.27                   py27_0  
pyasn1                    0.1.7                    py27_0  
pyaudio                   0.2.7                    py27_0  
pycosat                   0.6.1                    py27_0  
pycparser                 2.14                     py27_0  
pycrypto                  2.6.1                    py27_0  
pycurl                    7.19.5.1                 py27_2  
pyface                    4.4.0                    py27_0  
pyflakes                  0.9.2                    py27_0  
pygments                  2.0.2                    py27_0  
pylint                    1.4.3                     <pip>
pyopenssl                 0.15.1                   py27_1  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.3                   py27_0  
pytables                  3.2.0                np19py27_0  
pytest                    2.7.1                    py27_0  
python                    2.7.10                        1  
python-dateutil           2.4.2                    py27_0  
python.app                1.2                      py27_4  
pytz                      2015.4                   py27_0  
pyyaml                    3.11                     py27_1  
pyzmq                     14.7.0                   py27_0  
qt                        4.8.6                         3  
readline                  6.2                           2  
redis                     2.6.9                         0  
redis-py                  2.10.3                   py27_0  
requests                  2.8.0                    py27_0  
rope                      0.9.4                    py27_1  
runipy                    0.1.3                    py27_0  
scikit-image              0.11.3               np19py27_0  
scikit-learn              0.16.1               np19py27_0  
scipy                     0.15.1               np19py27_0  
selenium                  2.45.0                    <pip>
setuptools                18.4                     py27_0  
sip                       4.16.5                   py27_0  
six                       1.9.0                    py27_0  
snowballstemmer           1.2.0                    py27_0  
sockjs-tornado            1.0.1                    py27_0  
sphinx                    1.3.1                    py27_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py27_0  
spyder                    2.3.5.2                  py27_0  
spyder-app                2.3.5.2                  py27_0  
sqlalchemy                1.0.5                    py27_0  
sqlite                    3.8.4.1                       1  
ssl_match_hostname        3.4.0.2                  py27_0  
statsmodels               0.6.1                np19py27_0  
sympy                     0.7.6                    py27_0  
tables                    3.2.0                     <pip>
terminado                 0.5                      py27_0  
tk                        8.5.18                        0  
toolz                     0.7.2                    py27_0  
tornado                   4.2                      py27_0  
traits                    4.4.0                    py27_0  
traitsui                  4.4.0                    py27_0  
ujson                     1.33                     py27_0  
unicodecsv                0.9.4                    py27_0  
werkzeug                  0.10.4                   py27_0  
wheel                     0.26.0                   py27_1  
xlrd                      0.9.3                    py27_0  
xlsxwriter                0.7.3                    py27_0  
xlwings                   0.3.5                    py27_0  
xlwt                      1.0.0                    py27_0  
yaml                      0.1.6                         0  
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0  
iMac2:tax-calculator mrh$ 
```

**Comment by talumbau** [comment]
@martinholmer one thing might be to do a `conda update numba` since the version of numba you are using is a couple of versions old

**Comment by martinholmer** [comment]
@talumbau said:
> one thing might be to do a conda update numba since the version of numba you are using is a couple of versions old

OK, but that can't be the cause of the Travis-CI problem, can it?

**Comment by MattHJensen** [comment]
See #407. @GoFroggyRun actually had problem with anything beyond @martinholmer's current numba.

**Comment by talumbau** [comment]
Travis CI is running a version of 64 bit linux with with latest version of numba. When I duplicate that myself, I get the error (in other words, I created my own 64 bit linux machine with the latest numba). Also, when I run the test on my own mac with the latest numba, I get the error, so that seems like a reasonable culprit.

**Comment by martinholmer** [comment]
@talumbau ,  OK, I'm afraid to update numba on my computer given (what I understand to be) Sean's experience.  So, are we coming to the conclusion that the Travis-CI problem with test_3 in test_simpletaxio.py is caused because it is using a version of numba that is greater than 0.19.1?  If not, then I'm still confused.  But, if so, doesn't that mean that numba is pretty flaky?

**Comment by talumbau** [comment]
@martinholmer there is no need to fear updating numba on your computer. You can always do as follows:

```
conda remove numba
conda install numba=0.19
```

and then `conda update numba` again to get the latest. Also, you could just destroy/delete whatever conda environment you are using if you don't want to use it anymore. For example, we encourage people to use the `taxcalc-dev` environment they get when doing `conda env create` at the top of the Tax-Calculator repo. The environments are always disposable.

I'm not sure how one would conclude that numba is flaky. It's certainly possible that there is a bug in numba, but every commit to master is run on the Cartesian product of {numpy 1.6 - 1.10} X { python 2.6 -> 3.5} X { win32, win64, linux32, linux64, mac} (roughly). So, releases are vetted pretty well. My own hypothesis is that previously allowed "lowering" activity (say float64 -> int32) is no longer allowed for safety reasons, but I don't have the proof in front of me.

**Comment by martinholmer** [comment]
Pull request #404 resolves this issue, so it is being closed.

**Comment by talumbau** [comment]
An important post script is that the best practice for developers of the Tax-Calculator would be to use the most up-to-date version of numba.

**Comment by MattHJensen** [comment]
@talumbau, this means we can close #407 as well, right?

**Comment by talumbau** [comment]
yes we should close #407

**Comment by martinholmer** [comment]
@talumbau said:
> So, [numba] releases are vetted pretty well. My own hypothesis is that previously allowed "lowering" activity (say float64 --> int32) is no longer allowed for safety reasons, but I don't have the proof in front of me.

So, you're saying numba considers float64 --> int64 safe?

**Comment by talumbau** [comment]
> So, you're saying numba considers float64 --> int64 safe?

No. I am saying that numba has likely disallowed some kind of casting/type promotion rule that was previously allowed, presumably because that rule was deemed bad/unsafe for some reason. It could be that the rule is incorrect, or that it is too cautious, or inconsistent with other rules. Out of an abundance of caution, I will create a reproducer for this issue for the numba team, and let them analyze the difference in behavior between numba 0.19 and numba 0.21. Then we will have a definitive answer on the reason behind the change in behavior.
