### ISSUE TITLE
Massive test failures after "conda update numba"

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/Tax-Calculator#408]
@MattHJensen , @talumbau , @GoFroggyRun ,

I just followed T.J.'s recommendation and here is what happened on my iMac:
```
iMac2:tax-calculator mrh$ conda update numba
Fetching package metadata: ....
Solving package specifications: ................
Package plan for installation in environment /Users/mrh/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.10.1               |           py27_0         3.0 MB
    requests-2.8.1             |           py27_0         603 KB
    six-1.10.0                 |           py27_0          16 KB
    conda-3.18.3               |           py27_0         175 KB
    llvmlite-0.7.0             |           py27_3         6.4 MB
    singledispatch-3.4.0.3     |           py27_0          12 KB
    numba-0.21.0               |      np110py27_0         1.2 MB
    ------------------------------------------------------------
                                           Total:        11.4 MB

The following NEW packages will be INSTALLED:

    singledispatch: 3.4.0.3-py27_0    

The following packages will be UPDATED:

    conda:          3.18.2-py27_0     --> 3.18.3-py27_0     
    llvmlite:       0.5.0-py27_0      --> 0.7.0-py27_3      
    numba:          0.19.1-np19py27_0 --> 0.21.0-np110py27_0
    numpy:          1.9.2-py27_0      --> 1.10.1-py27_0     
    requests:       2.8.0-py27_0      --> 2.8.1-py27_0      
    six:            1.9.0-py27_0      --> 1.10.0-py27_0     

Proceed ([y]/n)? y

Fetching packages ...
numpy-1.10.1-p 100% |################################| Time: 0:00:00   4.32 MB/s
requests-2.8.1 100% |################################| Time: 0:00:00   2.18 MB/s
six-1.10.0-py2 100% |################################| Time: 0:00:00 933.40 kB/s
conda-3.18.3-p 100% |################################| Time: 0:00:00 925.39 kB/s
llvmlite-0.7.0 100% |################################| Time: 0:00:00   7.06 MB/s
singledispatch 100% |################################| Time: 0:00:00 603.92 kB/s
numba-0.21.0-n 100% |################################| Time: 0:00:00   2.89 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
iMac2:tax-calculator mrh$ conda update numba
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /Users/mrh/anaconda:
#
numba                     0.21.0              np110py27_0  
iMac2:tax-calculator mrh$ clear

iMac2:tax-calculator mrh$ ../pytests 
============================= test session starts ==============================
platform darwin -- Python 2.7.10 -- py-1.4.27 -- pytest-2.7.1
rootdir: /Users/mrh/work/OSPC/tax-calculator, inifile: setup.cfg
collected 93 items 

tests/test_behavior.py F..
tests/test_calculate.py FFF.FFF..FFFFFF
tests/test_decorators.py .................
tests/test_growth.py FFFF.
tests/test_policy.py ................
tests/test_records.py ...F..
tests/test_simpletaxio.py ...
tests/test_utils.py ......F.............FF......

=================================== FAILURES ===================================
```

What do I do to recover from this?

**Comment by GoFroggyRun** [comment]
@martinholmer `conda install numba=0.19.1` might resolve the issue. But not sure if it's a good way.

**Comment by MattHJensen** [comment]
Actually I think what you want is conda install numpy=1.9.3 per 
https://github.com/OpenSourcePolicyCenter/Tax-Calculator/blob/master/environment.yml, which should automatically downgrade everything else that needs to be downgraded. 

Even better, follow steps 9 and 10 from http://taxcalc.readthedocs.org/en/latest/contributor_guide.html which should automatically install the right dependencies in an environment you can use for tax-calculator development.

**Comment by martinholmer** [comment]
@GoFroggyRun said:
>  conda install numba=0.19.1 might resolve the issue. But not sure if it's a good way.

Sean, Thanks for the advice.  I thought @MattHJensen had closed your pull request because it was not needed and the Tax-Calculator would work with the newest version of numba?  And that is what @talumbau  told me to do as well.

**Comment by MattHJensen** [comment]
I think the issue is that upgrading numba upgraded you to a version of numpy that doesn't work. See #381 for discussion.

**Comment by martinholmer** [comment]
@MattHJensen said:
> Actually I think what you want is conda install numpy=1.9.3 per ...

Here is what happened:
```
iMac2:tax-calculator mrh$ conda install numpy=1.9.3
Fetching package metadata: ....
Solving package specifications: ....................
Package plan for installation in environment /Users/mrh/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.9.3                |           py27_0         2.9 MB

The following packages will be DOWNGRADED:

    numpy: 1.10.1-py27_0 --> 1.9.3-py27_0

Proceed ([y]/n)? y

Fetching packages ...
numpy-1.9.3-py 100% |################################| Time: 0:00:01   2.21 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
iMac2:tax-calculator mrh$ ../pytests 
============================= test session starts ==============================
platform darwin -- Python 2.7.10 -- py-1.4.27 -- pytest-2.7.1
rootdir: /Users/mrh/work/OSPC/tax-calculator, inifile: setup.cfg
collected 0 items / 8 errors 

==================================== ERRORS ====================================
_______________ ERROR collecting taxcalc/tests/test_behavior.py ________________
tests/test_behavior.py:7: in <module>
    from taxcalc import Policy, Records, Calculator, behavior, Behavior, Growth
__init__.py:1: in <module>
    from .calculate import *
calculate.py:7: in <module>
    from .functions import *
functions.py:6: in <module>
    from .decorators import *
decorators.py:5: in <module>
    from numba import jit, vectorize, guvectorize
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/__init__.py:7: in <module>
    from . import testing, decorators
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/decorators.py:9: in <module>
    from .targets import registry
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/targets/registry.py:3: in <module>
    from . import cpu
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/targets/cpu.py:11: in <module>
    from .base import BaseContext, PYOBJECT
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/targets/base.py:14: in <module>
    from numba import _dynfunc, _helperlib
E   ImportError: numpy.core.multiarray failed to import
------------------------------- Captured stderr --------------------------------
RuntimeError: module compiled against API version a but this version of numpy is 9
_______________ ERROR collecting taxcalc/tests/test_calculate.py _______________
tests/test_calculate.py:11: in <module>
    from taxcalc import Policy, Records, Calculator, Growth
__init__.py:1: in <module>
    from .calculate import *
calculate.py:7: in <module>
    from .functions import *
functions.py:6: in <module>
    from .decorators import *
decorators.py:5: in <module>
    from numba import jit, vectorize, guvectorize
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/__init__.py:7: in <module>
    from . import testing, decorators
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/decorators.py:7: in <module>
    from . import config, sigutils
E   ImportError: cannot import name config
______________ ERROR collecting taxcalc/tests/test_decorators.py _______________
tests/test_decorators.py:10: in <module>
    from numba import jit, vectorize, guvectorize
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/__init__.py:7: in <module>
    from . import testing, decorators
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/decorators.py:7: in <module>
    from . import config, sigutils
E   ImportError: cannot import name config
________________ ERROR collecting taxcalc/tests/test_growth.py _________________
tests/test_growth.py:8: in <module>
    from taxcalc import Policy, Records, Calculator, behavior, Behavior, Growth
__init__.py:1: in <module>
    from .calculate import *
calculate.py:7: in <module>
    from .functions import *
functions.py:6: in <module>
    from .decorators import *
decorators.py:5: in <module>
    from numba import jit, vectorize, guvectorize
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/__init__.py:7: in <module>
    from . import testing, decorators
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/decorators.py:7: in <module>
    from . import config, sigutils
E   ImportError: cannot import name config
________________ ERROR collecting taxcalc/tests/test_policy.py _________________
tests/test_policy.py:11: in <module>
    from numba import jit, vectorize, guvectorize
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/__init__.py:7: in <module>
    from . import testing, decorators
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/decorators.py:7: in <module>
    from . import config, sigutils
E   ImportError: cannot import name config
________________ ERROR collecting taxcalc/tests/test_records.py ________________
tests/test_records.py:7: in <module>
    from taxcalc import Records, imputed_cmbtp_itemizer, Policy, Calculator
__init__.py:1: in <module>
    from .calculate import *
calculate.py:7: in <module>
    from .functions import *
functions.py:6: in <module>
    from .decorators import *
decorators.py:5: in <module>
    from numba import jit, vectorize, guvectorize
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/__init__.py:7: in <module>
    from . import testing, decorators
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/decorators.py:7: in <module>
    from . import config, sigutils
E   ImportError: cannot import name config
______________ ERROR collecting taxcalc/tests/test_simpletaxio.py ______________
tests/test_simpletaxio.py:12: in <module>
    from taxcalc import SimpleTaxIO  # pylint: disable=import-error
__init__.py:1: in <module>
    from .calculate import *
calculate.py:7: in <module>
    from .functions import *
functions.py:6: in <module>
    from .decorators import *
decorators.py:5: in <module>
    from numba import jit, vectorize, guvectorize
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/__init__.py:7: in <module>
    from . import testing, decorators
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/decorators.py:7: in <module>
    from . import config, sigutils
E   ImportError: cannot import name config
_________________ ERROR collecting taxcalc/tests/test_utils.py _________________
tests/test_utils.py:15: in <module>
    from numba import jit, vectorize, guvectorize
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/__init__.py:7: in <module>
    from . import testing, decorators
/Users/mrh/anaconda/lib/python2.7/site-packages/numba/decorators.py:7: in <module>
    from . import config, sigutils
E   ImportError: cannot import name config
=========================== 8 error in 4.68 seconds ============================
iMac2:tax-calculator mrh$ 
```

**Comment by MattHJensen** [comment]
Just ran conda update numba on my machine now so that we can be working on the same problem shortly.

**Comment by MattHJensen** [comment]
Ok, @martinholmer, I got the same error as you after upgrading numba and then running `conda install numpy = 1.9.3`. 

I was also able to confirm that, even after getting myself into this dependency mess, following the directions in our user docs to run `conda env create` from `\tax-calculator` and then using that environment (`source activate taxcalc-dev`) got everything working again. 

My plan now is to compare `conda list` from my taxcalc-dev environment to `conda list` from the regular, now buggy, environment, and see what the differences are.

**Comment by MattHJensen** [comment]
# packages in environment at /Users/Matt.Jensen/anaconda/envs/taxcalc-dev:
#
apipkg                    1.4                       <pip>
appnope                   0.1.0                    py27_0  
backports.ssl-match-hostname 3.4.0.2                   <pip>
certifi                   14.05.14                 py27_0  
decorator                 4.0.4                    py27_0  
enum34                    1.0.4                    py27_0  
execnet                   1.4.1                     <pip>
funcsigs                  0.4                      py27_0  
ipykernel                 4.1.0                    py27_0  
ipython                   4.0.0                    py27_1  
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py27_0  
ipython_genutils          0.1.0                    py27_0  
jinja2                    2.8                      py27_0  
jsonschema                2.4.0                    py27_0  
jupyter-client            4.1.1                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py27_0  
jupyter_core              4.0.6                    py27_0  
libsodium                 0.4.5                         0  
llvmlite                  0.7.0                    py27_3  
markupsafe                0.23                     py27_0  
mistune                   0.7.1                    py27_0  
nbconvert                 4.0.0                    py27_0  
nbformat                  4.0.1                    py27_0  
notebook                  4.0.6                    py27_0  
numba                     0.21.0               np19py27_0  
numpy                     1.9.3                    py27_0  
openssl                   1.0.1k                        1  
pandas                    0.16.1               np19py27_0  
path.py                   8.1.2                    py27_0  
pep8                      1.6.2                     <pip>
pexpect                   3.3                      py27_0  
pickleshare               0.5                      py27_0  
pip                       7.1.2                    py27_0  
ptyprocess                0.4                      py27_0  
py                        1.4.30                   py27_0  
pygments                  2.0.2                    py27_0  
pytest                    2.8.1                    py27_0  
pytest-cache              1.0                       <pip>
pytest-pep8               1.0.6                     <pip>
python                    2.7.10                        1  
python-dateutil           2.4.2                    py27_0  
python.app                1.2                      py27_4  
pytz                      2015.6                   py27_0  
pyzmq                     14.7.0                   py27_0  
readline                  6.2                           2  
setuptools                18.4                     py27_0  
simplegeneric             0.8.1                    py27_0  
singledispatch            3.4.0.3                  py27_0  
six                       1.10.0                   py27_0  
sqlite                    3.8.4.1                       1  
ssl_match_hostname        3.4.0.2                  py27_0  
terminado                 0.5                      py27_0  
tk                        8.5.18                        0  
toolz                     0.7.4                    py27_0  
tornado                   4.2.1                    py27_0  
traitlets                 4.0.0                    py27_0  
wheel                     0.26.0                   py27_1  
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0  
(taxcalc-dev)lham-bgx0yv1-d:taxcalc Matt.Jensen$ source deactivate taxcalc-dev
Error: too many arguments.
(taxcalc-dev)lham-bgx0yv1-d:taxcalc Matt.Jensen$ source deactivate
discarding /Users/Matt.Jensen/anaconda/envs/taxcalc-dev/bin from PATH
lham-bgx0yv1-d:taxcalc Matt.Jensen$ conda list
# packages in environment at /Users/Matt.Jensen/anaconda:
#
_license                  1.1                      py27_0  
abstract-rendering        0.5.1                np19py27_0  
alabaster                 0.7.3                    py27_0  
anaconda                  2.2.0                np19py27_0  
appnope                   0.1.0                    py27_0  
appscript                 1.0.1                    py27_0  
argcomplete               0.8.4                    py27_0  
astropy                   1.0.1                np19py27_0  
atom                      0.3.9                    py27_0  
babel                     1.3                      py27_0  
backports.ssl-match-hostname 3.4.0.2                   <pip>
bcolz                     0.8.1                np19py27_0  
beautiful-soup            4.3.2                    py27_0  
beautifulsoup4            4.3.2                     <pip>
binstar                   0.10.1                   py27_3  
bitarray                  0.8.1                    py27_0  
blaze                     0.6.3                np19py27_0  
blaze-core                0.7.3                np19py27_0  
blessings                 1.6                       <pip>
blz                       0.6.2                np19py27_0  
bokeh                     0.9.2                np19py27_0  
boto                      2.36.0                   py27_0  
casuarius                 1.1                      py27_0  
cdecimal                  2.3                      py27_0  
certifi                   14.05.14                 py27_0  
cffi                      0.9.2                    py27_0  
chaco                     4.4.1                np19py27_0  
clyent                    0.3.4                    py27_0  
colorama                  0.3.3                    py27_0  
conda                     3.18.3                   py27_0  
conda-build               1.8.2                    py27_0  
conda-env                 2.4.2                    py27_0  
configobj                 5.0.6                    py27_0  
cryptography              0.8                      py27_0  
curl                      7.38.0                        0  
cython                    0.22                     py27_0  
cytoolz                   0.7.2                    py27_0  
datashape                 0.4.4                np19py27_1  
dateutil                  2.4.1                    py27_0  
decorator                 4.0.4                    py27_0  
docopt                    0.6.2                     <pip>
docutils                  0.12                     py27_0  
dynd-python               0.6.5                np19py27_0  
enable                    4.3.0                np19py27_2  
enaml                     0.9.8                    py27_0  
enum34                    1.0.4                    py27_0  
fastcache                 1.0.2                    py27_0  
fdfgen                    0.11.0                    <pip>
flake8                    2.3.0                    py27_0  
flask                     0.10.1                   py27_1  
freetype                  2.4.10                        1  
funcsigs                  0.4                      py27_0  
future                    0.13.1                   py27_0  
futures                   2.2.0                    py27_0  
gevent                    1.0.1                    py27_0  
gevent-websocket          0.9.3                    py27_0  
greenlet                  0.4.7                    py27_0  
grin                      1.2.1                    py27_1  
h5py                      2.4.0                np19py27_0  
hdf5                      1.8.14                        0  
ipykernel                 4.0.3                    py27_0  
ipython                   4.0.0                    py27_1  
ipython-genutils          0.1.0                     <pip>
ipython-notebook          3.0.0                    py27_1  
ipython-qtconsole         3.0.0                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                4.0.3                    py27_0  
itsdangerous              0.24                     py27_0  
jdcal                     1.0                      py27_0  
jedi                      0.8.1                    py27_0  
jinja2                    2.8                      py27_0  
jpeg                      8d                            1  
jsonschema                2.4.0                    py27_0  
jupyter                   1.0.0                    py27_0  
jupyter-client            4.0.0                     <pip>
jupyter-console           4.0.2                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.0.0                    py27_0  
jupyter_console           4.0.2                    py27_0  
jupyter_core              4.0.6                    py27_0  
kiwisolver                0.1.3                    py27_0  
launcher                  1.0.0                         2  
lcms                      1.19                          0  
libdynd                   0.6.5                         0  
libpng                    1.5.13                        1  
libsodium                 0.4.5                         0  
libtiff                   4.0.2                         1  
libxml2                   2.9.0                         1  
libxslt                   1.1.28                        2  
llvm                      3.3                           0  
llvmlite                  0.7.0                    py27_3  
llvmpy                    0.12.7                   py27_0  
luca                      1.0                       <pip>
lxml                      3.4.2                    py27_0  
markupsafe                0.23                     py27_0  
matplotlib                1.4.2                np19py27_0  
mccabe                    0.3                      py27_1  
mistune                   0.7.1                    py27_0  
mock                      1.0.1                    py27_0  
multipledispatch          0.4.7                    py27_0  
nbconvert                 4.0.0                    py27_0  
nbformat                  4.0.0                    py27_0  
networkx                  1.9.1                    py27_0  
nltk                      3.0.2                np19py27_0  
node-webkit               0.10.1                        0  
nose                      1.3.4                    py27_1  
notebook                  4.0.5                    py27_0  
numba                     0.21.0              np110py27_0  
numexpr                   2.3.1                np19py27_0  
numpy                     1.9.3                    py27_0  
odo                       0.3.1                np19py27_0  
openpyxl                  1.8.5                    py27_0  
openssl                   1.0.1k                        1  
pandas                    0.16.2               np19py27_0  
path.py                   8.1.2                    py27_0  
patsy                     0.3.0                np19py27_0  
pep8                      1.6.2                    py27_0  
pexpect                   3.3                      py27_0  
pickleshare               0.5                      py27_0  
pil                       1.1.7                    py27_1  
pillow                    2.7.0                    py27_1  
pip                       7.1.2                    py27_0  
ply                       3.4                      py27_0  
pockets                   0.2.4                     <pip>
psutil                    2.2.1                    py27_0  
ptyprocess                0.4                      py27_0  
py                        1.4.27                   py27_0  
pyasn1                    0.1.7                    py27_0  
pyaudio                   0.2.7                    py27_0  
pycosat                   0.6.1                    py27_0  
pycparser                 2.10                     py27_0  
pycrypto                  2.6.1                    py27_0  
pycurl                    7.19.5.1                 py27_0  
pyface                    4.4.0                    py27_0  
pyflakes                  0.9.2                    py27_0  
pygments                  2.0.2                    py27_0  
pyopenssl                 0.14                     py27_0  
pyparsing                 2.0.1                    py27_0  
pypdf                     1.13                      <pip>
pyqt                      4.11.4                   py27_0  
pytables                  3.1.1                np19py27_2  
pytest                    2.7.1                    py27_0  
python                    2.7.10                        1  
python-dateutil           2.4.2                    py27_0  
python.app                1.2                      py27_4  
pytz                      2015.6                   py27_0  
pyyaml                    3.11                     py27_1  
pyzmq                     14.7.0                   py27_0  
qt                        4.8.7                         1  
qtconsole                 4.0.1                    py27_0  
readline                  6.2                           2  
redis                     2.6.9                         0  
redis-py                  2.10.3                   py27_0  
reportlab                 3.2.0                     <pip>
requests                  2.8.1                    py27_0  
rope                      0.9.4                    py27_1  
runipy                    0.1.3                    py27_0  
scikit-image              0.11.2               np19py27_0  
scikit-learn              0.15.2               np19py27_0  
scipy                     0.15.1               np19py27_0  
setuptools                18.4                     py27_0  
simplegeneric             0.8.1                    py27_0  
singledispatch            3.4.0.3                  py27_0  
sip                       4.16.9                   py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.0                    py27_0  
sockjs-tornado            1.0.1                    py27_0  
sphinx                    1.3.1                    py27_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py27_0  
spyder                    2.3.4                    py27_1  
spyder-app                2.3.4                    py27_0  
sqlalchemy                0.9.9                    py27_0  
sqlite                    3.8.4.1                       1  
ssl_match_hostname        3.4.0.2                  py27_0  
statsmodels               0.6.1                np19py27_0  
sympy                     0.7.6                    py27_0  
tables                    3.1.1                     <pip>
terminado                 0.5                      py27_0  
tk                        8.5.18                        0  
toolz                     0.7.2                    py27_0  
tornado                   4.2.1                    py27_0  
traitlets                 4.0.0                    py27_0  
traits                    4.4.0                    py27_0  
traitsui                  4.4.0                    py27_0  
ujson                     1.33                     py27_0  
unicodecsv                0.9.4                    py27_0  
werkzeug                  0.10.4                   py27_0  
wheel                     0.26.0                   py27_1  
xlrd                      0.9.3                    py27_0  
xlsxwriter                0.6.7                    py27_0  
xlwings                   0.3.4                    py27_0  
xlwt                      0.7.5                    py27_0  
yaml                      0.1.6                         0  
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0

**Comment by MattHJensen** [comment]
Looks like Pandas is the main difference, and I see that in  `environment.yml`, we have `- pandas <=0.16.1`

@martinholmer, if you do not want to create a new environment from scratch, you might try from where you are now:

`conda install pandas = 0.16.1`

That said, I think the most stable approach for us would be to pin versions of most packages in environment.yml, follow the user directions about using a taxcalc-dev environment, and then periodically and deliberatively move the pins to newer versions and check to make sure nothing is broken and fix anything that is when we move those pins.

**Comment by talumbau** [comment]
Ah, I see the problem. Here is the version of `numba` you get when you just specify `conda update numba`:

numba 0.21.0 np110py27_0

That version of `numba` is compiled against the latest numpy (thus the `np110` in the version string). Then when you change out the `numpy` version, the two versions are incompatible. I think the right sequence of commands would be:

```
conda remove numba
conda remove numpy
conda install numba=0.21 numpy=1.9.3
```

this would give conda the constraint that it needs to make sure you get the version of numba that is compiled against numpy 1.9.3

**Comment by MattHJensen** [comment]
Yes, just found that `conda install pandas = 0.16.1` doesn't work

**Comment by talumbau** [comment]
You should see this when listing the version of numba via `conda list`

```
numba                     0.21.0               np19py27_0

```

**Comment by talumbau** [comment]
Pinning the versions does help, but the key is to make sure that constraints are satisfied. In our case, we have a constraint that we can't go beyond numpy 1.9.3, which we have already pinned in our environment. In this case, I told Martin that `conda update numba` would be fine to do. I forgot about our constraint of staying on numpy 1.9, so I should've told Martin to do `conda update numba numpy=1.9.3` or similar so that he would get the latest numba that still satisfied that constraint. My apologies for causing all the fuss.

**Comment by martinholmer** [comment]
Doing this following got me back in business:
```
conda remove numba
conda remove numpy
conda install numba=0.21 numpy=1.9.3
```
Thanks @talumbau and @MattHJensen for all the help.

Is there are reason why the OSPC Tax-Calculator code does not work with the most recent versions of the tools being used in the project?

**Comment by talumbau** [comment]
We are stuck on numpy 1.9.3 due to this issue:

https://github.com/OpenSourcePolicyCenter/Tax-Calculator/issues/381

It's not exactly clear the right way to proceed, but Matt has expressed a preference for how we should move forward.

**Comment by martinholmer** [comment]
OK. Thanks for the background info.
