### ISSUE TITLE
Decide where to use bools

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/Tax-Calculator#62]
We may want to change some variable types to bool. This could make sense for existing variables like `_hasgain`.

If we do this, we can change

    if e01000 > 0 or c23650 > 0 or e23250 > 0 or e01100 > 0 or e00650 > 0:
        _hasgain = 1
    else: _hasgain = 0

to

    _hasgain = (e01000 > 0 or c23650 > 0 or e23250 > 0 or e01100 > 0 or e00650 > 0)

and 

    if _hasgain == 1:

to

    if _hasgain:

**Comment by talumbau** [comment]
I no longer think this is relevant. @MattHJensen any input?

**Comment by MattHJensen** [comment]
Agreed.
