### ISSUE TITLE
What is the _cmp variable for?

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#67]
The variable `_cmp` is only involved in comparison expressions (i.e. `where(_cmp == 1...`). It appears that it is never assigned to except when it is created in `puf.py`, where it is set to all zeros. Does anyone have any insight here? I'd like to remove it if it is not actually useful for any comparisons.

**Comment by MattHJensen** [comment]
Closing in favor of #186.
