### ISSUE TITLE
The current model doesn't account for 10 budget years

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#72]
In order to use the current code to model 10 budget years, we need data in the model for each year of the 10 years. In the current package, the code is structured to handle multiple years, it's just that we only index one year of data. If we were to attempt to index another year of data, we would get run time errors. For example, there is a lot of code like this:

```
 _prexmp = XTOT * _amex[FLPDYR - DEFAULT_YR]
```

`_amex` is defined like this:

```
_amex = np.array([3900])
```

So we are OK as long as `FLPDYR` is the same as `DEFAULT_YR`. Once we advance `FLPDYR`, then the model would no longer work. 

What is the best way to handle this situation for now (e.g. repeat the model parameters for 10 years), and is there a longer term solution that is different from the short term solution?

**Comment by MattHJensen** [comment]
resolved. closing.
