### ISSUE TITLE
Is it meaningful to have puf=False?

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#90]
In our current `test.py`, the `run` function has a keyword argument `puf` with a default value of `True`. All of our tests use this value. In `ItemDed`, we have this snippet of code:

```
    c20750 = 0.02 * _posagi
    if puf == True:
        c20400 = e20400
        c19200 = e19200
    else:
        c20400 = e20550 + e20600 + e20950
        c19200 = e19500 + e19570 + e19400 + e19550
    c20800 = np.maximum(0, c20400 - c20750)
```

Do we ever take the `else` branch here? If not, let's get rid of this check and remove the `puf` Boolean variable.

**Comment by feenberg** [comment]
On Mon, 12 Jan 2015, T.J. Alumbaugh wrote:

> 
> In our current test.py, the run function has a keyword argument puf with a
> default value of True. All of our tests use this value. In ItemDed, we have
> this snippet of code:
>
>     c20750 = 0.02 * _posagi
>     if puf == True:
>         c20400 = e20400
>         c19200 = e19200
>     else:
>         c20400 = e20550 + e20600 + e20950
>         c19200 = e19500 + e19570 + e19400 + e19550
>     c20800 = np.maximum(0, c20400 - c20750)
> 
> Do we ever take the else branch here? If not, let's get rid of this check
> and remove the puf Boolean variable.

I think the point is that in the future, we will give the code to someone 
with access to the complete (INSOLE) file, and they will set puf==False. 
There should be numerous places where this makes a difference.

dan

**Comment by talumbau** [comment]
Ah, thanks Dan. I will leave this in and handle with default keyword arguments for now. Closing.
