### ISSUE TITLE
Is _ymax indexed correctly in the current master?

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#93]
A number of parameters in the calculator are of the form:

```
#                    singl   joint   sep     hh      widow   sep
_phase2 = np.array([[250000, 300000, 150000, 275000, 300000, 150000],
                    [254200, 305050, 152525, 279650, 305050, 152525],
                    [258250, 309900, 154950, 284050, 309900, 154950],])
```
The outer dimension is for indexing by years. So `_phase2[0,1]` would be the index for the 'zeroth' budget year we are considering, and then the entry for "joint". 

Indexing usually looks like this:

```
 _phase2 = p._phase2[FLPDYR-p.DEFAULT_YR, MARS-1]
```
Where we subtract the default starting year from the filing year for each record.
This pattern holds throughout the calculator except for the `_ymax` variable. It looks like this:

```
#                    0kids 1kid   2kids  3+kids
_ymax = np.array([  [7970, 17530, 17530, 17530],
                    [8110, 17830, 17830, 17830],
                    [8240, 18110, 18110, 18110]]) 
```

But the indexing is different. In current master, the indexing looks like this (starting at line 1066):

```
   _val_ymax = np.where(np.logical_and(MARS == 2, _modagi > 0), p._ymax[
                         _ieic, FLPDYR - p.DEFAULT_YR] + p._joint[FLPDYR - p.DEFAULT_YR, _ieic], 0)
    _val_ymax = np.where(np.logical_and(_modagi > 0, np.logical_or(MARS == 1, np.logical_or(
        MARS == 4, np.logical_or(MARS == 5, MARS == 7)))), p._ymax[_ieic, FLPDYR - p.DEFAULT_YR], _val_ymax)
```

So, `_ymax` has the "year" index second. I think this is an error. Correct? @feenberg @MattHJensen

**Comment by MattHJensen** [comment]
That is correct, @talumbau.

**Comment by talumbau** [comment]
Ok thanks. Fixed in https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/88
