### ISSUE TITLE
Reference IRS forms in parameters.py

### ISSUE THREAD

**Issue by Amy-Xu** [OpenSourcePolicyCenter/Tax-Calculator#94]
I added some comments to parameters.py to provide the parameters with references to IRS forms and worksheets. I confirmed the accuracy of parameters for 2014 and labeled where to find each parameter in the same format. This is meant to make it easier for others to find/calculate the parameters from IRS forms and to make it easier for us to update the calculator in the future.

Please let me know if you have any suggestions on formatting the IRS reference comments. 

Link to the file on my fork: https://github.com/Amy-Xu/Tax-Calculator/blob/master/taxcalc/parameters.py  (illustrations of comments can be found at the beginning of the file)

@feenberg I changed one parameter at line 205, the threshold for additional medicare tax for widows, from 250,000 to 200,000 (_thresx[MARS==5]). Here’s the IRS page I refer to: http://www.irs.gov/uac/Newsroom/What-You-Should-Know-about-the-Additional-Medicare-Tax. Could you please check? I hope I read the right source. Thanks a lot!

Thanks,
Amy

**Comment by talumbau** [comment]
Amy,

This is great content. I think it will be really helpful for users. I was in the middle of refactoring `parameters.py` as this came up, and my refactored version is now in master. Please feel free to modify it as you think would be helpful.

My thoughts are that we would want these comments to be such that a tool could automatically pull them out if desired. Something like Python doc strings. I don't have a concrete suggestion yet. Just a heads up.

**Comment by Amy-Xu** [comment]
@MattHJensen we have already dealt with this in params.json right? Can we close this issue?

**Comment by MattHJensen** [comment]
Could you check that we aren't missing any first?

**Comment by Amy-Xu** [comment]
you mean we should fill all the IRS references before closing this issue?

**Comment by MattHJensen** [comment]
Alternatively, I could open a larger "documentation" issue where we consolidate many of our documentation to dos. What do you think of that?

**Comment by Amy-Xu** [comment]
Sounds good to me. The content of this issue is outdated in terms of how we store and retrieve parameters. We need a more updated list of tasks for documentation. Should we include #123 as well in that new issue?

**Comment by MattHJensen** [comment]
Closing in favor of #244.
