### ISSUE TITLE
Parameterize hard-coded variables

### ISSUE THREAD

**Issue by Amy-Xu** [OpenSourcePolicyCenter/Tax-Calculator#98]
For the hard-coded variables in functions.py, I came up with some naming conventions to parameterize them, which should be universal and flexible enough to apply to other parameters in parameters.py at some point.

The variable names generally have two fixed components, one for tax/tax credit category (upper case) and the other for the function of this number in calculation (lower case). 

--------------------------------
The category names so far include the following:

CTC: Child Tax Credit
ACTC: Additional Child Tax Credit
AMT: Alternative Minimum Tax
II: Individual Income (Including personal exemptions and tax brackets)
CG: Capital Gain
EITC: Earned Income Tax Credit
ETC: Education Tax Credit
FEI: Foreign Earned Income
ID: Itemized Deduction
STD: Standard Deduction
FICA: Federal Income Contributions Act
SS: Social Security
MED: Medicare
AMED: Additional Medicare

--------------------------------
The possible functions of HC numbers:

c: ceiling
f: floor
t: tax
p: phaseout
rt: rate
em: exemption
ec: exclusion
thd: threshold

For example, the FICA tax rate would be _FICA_trt, t for tax and rt for rate. Similarly, prt represents a phaseout rate, crt represents a ceiling rate etc. 

In addition to these two essential components, there might be sub-components to make the var names more informational. For example, _ID_Madical_frt refers to the medical deduction floor rate under Itemized Deduction. All these subcomponents should be very intuitive that people don’t need a reference to understand their meanings. 

All above is what I came up with at this point. Please let me know if you have any suggestions on the format/abbreviation.

I added some hard coded values at the end of parameters.py and revised the corresponding section in functions.py. Here are the links to the modified files:  functions.py (https://github.com/Amy-Xu/Tax-Calculator/blob/master/taxcalc/functions.py) and parameters.py (https://github.com/Amy-Xu/Tax-Calculator/blob/master/taxcalc/parameters.py).

Here's a list of the parameters I created:

![list_params](https://cloud.githubusercontent.com/assets/10549597/5907886/aeb46ab8-a570-11e4-8b01-e3c4716e3f12.png)

**Comment by MattHJensen** [comment]
@amy-xu, since we are adopting this naming convention in #143, could you use whatever information from this issue you think is relevant to make a .md document for the docs folder that describes the convention?

**Comment by Amy-Xu** [comment]
Yes. Will do.

**Comment by MattHJensen** [comment]
Closing this because @rkuchan incorporated this nomenclature in #255.
